### ISSUE TITLE
Videos are no longer listed by date (most recent on top)

### ISSUE THREAD

**Issue by stevenvolckaert** [pietje666/plugin.video.vrt.nu#10]
Videos of a specific series (e.g. [Het journaal][2]) used to be listed in the order that they appeared on [VRT.NU][1]. This was quite useful, as the most recent video would always appear at the top of the list.

Since commit fa794232a5c8f73ba9221dfb87d0a54bccde3510, which fixed issue #2, the videos seem to be sorted alphabetically. When the episode list of a series that has a lot of episodes (e.g. [Het journaal][2] contains around 90 episodes), the user needs to scroll down, searching for the most recent episode.

### Notes

- I couldn't immediately find the cause of this behavior change in commit fa794232a5c8f73ba9221dfb87d0a54bccde3510. It could have been introduced to changes in Kodi or the [VRT.NU][1] website.
- I didn't have the chance yet to check if HEAD of [master][3] has this problem too.

[1]: https://www.vrt.be/vrtnu/
[2]: https://www.vrt.be/vrtnu/a-z/het-journaal/2017/het-journaal-d20170726-het-journaal-laat/
[3]: https://github.com/pietje666/plugin.video.vrt.nu

**Comment by pietje666** [comment]
I think i know why, it is because of the KodiWrapper. 
It adds it by alphabet by default

    def show_listing(self, list_items):
        listing = []
        for title_item in list_items:
            list_item = xbmcgui.ListItem(label=title_item.title)
            url = self._url + '?' + urlencode(title_item.url_dictionary)
            list_item.setProperty('IsPlayable', str(title_item.is_playable))

            if title_item.thumbnail is not None:
                list_item.setArt({'thumb': title_item.thumbnail})

            list_item.setInfo('video', title_item.video_dictionary)

            listing.append((url, list_item, not title_item.is_playable))
        xbmcplugin.addDirectoryItems(self._handle, listing, len(listing))
        xbmcplugin.addSortMethod(self._handle, xbmcplugin.SORT_METHOD_LABEL_IGNORE_THE)
        xbmcplugin.endOfDirectory(self._handle)

fix is just adding the parameter to the method show_listing

**Comment by pietje666** [comment]
Fixed in commit 8cd6f39  Feel free to test the fix

Will probably wait one more week before merging to kodi addon repository

**Comment by stevenvolckaert** [comment]
Thanks for the fix! I won't be able to test, though; I'm on holiday abroad.

Cheers!

**Comment by stevenvolckaert** [comment]
Tested this yesterday: The videos are sorted again like they appear on the VRT.NU website.

Thanks for fixing!
