### ISSUE TITLE
Move to using script.module.routing

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#103]
**Describe the bug**
Yesterday I stumbled on **plugin.video.fosdem** and I was charmed by how simple and easy the code was to understand. Now I am convinced we ought to be using **script.module.routing** as well (I added it to the refactoring roadmap).

See https://github.com/jelly/plugin.video.fosdem/blob/master/addon.py#L56

More information related to **script.module.routing**: 
- Documentation: https://github.com/tamland/kodi-plugin-routing
- Tutorial: https://github.com/afrase/kodiswift/blob/master/docs/tutorial.rst

**Comment by pietje666** [comment]
Actually when i saw your improvement i wanted to post that i know that this exists. But i never came to implement it. But it is alot better indeed. Just never came to implement it

**Comment by dagwieers** [comment]
It is not bad to take small steps as long as we know where we are heading at.
And only rarely you are in the situation that everyone has the same overall vision.
I feel it is the case in this project. That helps :-)

**Comment by dagwieers** [comment]
So looking into this a bit deeper, if we go along this path it will break every internal URL from the past (so favourites and watched information will break). So this will probably be v2.0.0 material.

We also have to come up with a design for the different routes, I would prefer something more coherent than what we already have. Something like this:

- **/** *(aka. main-menu)*
- **/categories**
  - category=&lt;name&gt; *(optional)*
- **/live-tv**
  - channel=&lt;name&gt; *(optional)*
- **/play**
  - videoid=&lt;id&gt; *(optional)*
- **/programs** *(aka. az-listing)*
  - program=&lt;name&gt; *(optional)*
  - season=&lt;season&gt; *(optional)*
- **/recent**
  - page=&lt;nr&gt; *(optional)*

These entries would be self-sufficient and reuse more generic functionality.

**Comment by mediaminister** [comment]
Like a said in https://github.com/pietje666/plugin.video.vrt.nu/pull/300#issuecomment-500790502:
The play interface needs two parameters for VOD: `video_id` and `publication_id`.
So if I follow your syntax you suggested above, this will result in the following urls:

This will work with the current workflow of the add-on:

VOD without web scraping (fast start of playback):
**/play/id/<publication_id>/<video_id>**
_/play/id/pbs-pub-10a01230-3b0b-4921-9936-cfa7e97f7dd0/vid-b133c2ad-d847-4eaa-8158-92fd9f072c8a_

VOD with web scraping (slower start of playback):
**/play/video/<video_url>**
_/play/video/https://<span></span>www.vrt.be/vrtnu/a-z/de-campus-cup/1/campus-cup-s1a9/_

LIVE without web scraping (fast start of playback):
**/play/id/<video_url>**
_/play/id/vualto_een_geo_

LIVE with web scraping (slower start of playback)
**/play/video/<video_url>**
_/play/video/https://<span></span>www.vrt.be/vrtnu/kanalen/een/_

But, this doesn't really improve the current interface. Asking for `video_id` and `publication_id` or a full `video_url` is still very user unfriendly.

If we completely rethink the add-on workflow, we could make the following work:

**/play/<<span></span>program>/<<span></span>season>/<<span></span>episode>**
_/play/de-campus-cup/1/9_

Or a live channel
_/play/een_

I will investigate the second option.

**Comment by dagwieers** [comment]
Yes, I would prefer we have a unique sequence for each different input:
- /play/id/<pub_id>/<vid_id>
- /play/url/<vid_url>
- /play/vualto/<vualto_string>

But I prefer the second interface, if that is at all possible. We should make something that we can be sure will work regardless of what backend changes will come in the future. Even if that means translating to/from before/after a call.

**Comment by mediaminister** [comment]
I investigated the second interface but for a lot of programs I couldn't ensure that the play url's were completely unique. VRT Search api is a real mess, some programs have no or a wrong episode numbers and I couldn't find a unique correspondence between a vrtnu url and titles or shortdescription variables/

So, I implemented the first interface and made a pull request.

**Comment by dagwieers** [comment]
I am genuinely happy we did this, sooner rather than later. But since this breaks existing bookmarks and forgets what was watched we may want to communicate this differently. We have a few options (in order of importance/likeliness):

1. Communicate beforehand on Facebook, or as part of the changelog/addon description
2. Provide a one-time popup for people that upgraded the addon (can we intercept/detect this ?)
3. Add a backward-compatibility layer for existing bookmarks so they keep on working
4. Rewrite the database to reformat watched items from VRT NU

But the way it looks today, I think we can prepare for a v2.0.0 release, rather than do a v1.10.1 update.
