### ISSUE TITLE
Categories no longer works

### ISSUE THREAD

**Issue by Brutalious** [pietje666/plugin.video.vrt.nu#105]
**Describe the bug**
When I go to categories, "Nieuws en actua" => "Het journaal" it start loading 3 times but it never starts playing. I had this problem yesterday and the day before. Last week I had no problem with opening it this way.

**To Reproduce**
1. Go to 'Categories'
2. Click on 'Nieuws en activa'
3. Click on 'Het journaal'
4. error loading

**Expected behavior**
Start playing video 'Het journaal'

**(please complete the following information):**
 - Operating system: Android TV 8.1 oreo
 - Kodi Version: Kodi 18.1 Leia

**Additional context**
- Using a VPN: No
- Country you are using the addon from: Belgium

**Comment by dagwieers** [comment]
Did you try with the new 1.7.0 release? We improved the addon so that it uses the VRT.NU API more and it relies less on web scraping. Yesterday VRT.NU changes to the website caused 1.6.0 to fail.

**Comment by dagwieers** [comment]
I can confirm that with version 1.7.0 today it works fine to list and play "Het journaal". I tested the first few episodes only.

**Comment by Brutalious** [comment]
No I'll try it this evening, I'm still using version 1.6.0

**Comment by Brutalious** [comment]
Everything works now, update is great! Except "Het journaal" still won't start but I also have problems with the app for phone. So I guess the problem lied with VRT itself.

**Comment by dagwieers** [comment]
@Brutalious You will have to provide me with more information to what exact "Het Journaal" you are trying to play so I can try the exact same streams. Date and hour would help.
