### ISSUE TITLE
Add 3 screenshots to the add-on

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#107]
**Describe the bug**
Our listing on the Kodi website, as well as the add-on entry in the Kodi Add-on browser would look a lot nicer if it included 3 screenshots of the add-on.

So we need to select the 3 best views of the VRT.NU add-on that showcase it best:
- Main menu
- Video listing
- Live TV menu

Or any better suggestions?

**Comment by dagwieers** [comment]
I made the following screenshots:
![screenshot-01](https://user-images.githubusercontent.com/388198/55083787-5d331c00-50a4-11e9-80ae-5a714bb5ace6.png)
![screenshot-02](https://user-images.githubusercontent.com/388198/55083788-5d331c00-50a4-11e9-91a4-1d14eb8c92f4.png)
![screenshot-03](https://user-images.githubusercontent.com/388198/55083790-5dcbb280-50a4-11e9-91b1-ccf62a76370e.png)

**Comment by dagwieers** [comment]
Proposing 360p images instead to reduce size.
![screenshot-01](https://user-images.githubusercontent.com/388198/55084753-c1a2ab00-50a5-11e9-820a-77a489e33edb.png)
![screenshot-02](https://user-images.githubusercontent.com/388198/55084752-c1a2ab00-50a5-11e9-9a1e-18f3f9191133.png)
![screenshot-03](https://user-images.githubusercontent.com/388198/55084751-c10a1480-50a5-11e9-952c-f05fc2e66669.png)

**Comment by Brutalious** [comment]
Looks great!

**Comment by dagwieers** [comment]
So, @mediaminister suggested using pngquant, and here are the 720p images considerably reduced in size !!
![screenshot01](https://user-images.githubusercontent.com/388198/55200838-674a3d00-51c0-11e9-8b2e-9e71c191e714.png)
![screenshot02](https://user-images.githubusercontent.com/388198/55200837-66b1a680-51c0-11e9-8895-eb4b0228e382.png)
![screenshot03](https://user-images.githubusercontent.com/388198/55200836-66b1a680-51c0-11e9-89ee-7ed2a000ac3a.png)

**Comment by dagwieers** [comment]
Even better sizes, using:

    pngquant --posterize 0 --quality 65 --speed 1 --force live-tv.png

results in:

![screenshot01](https://user-images.githubusercontent.com/388198/55201536-b9d92880-51c3-11e9-8643-c559bd21ae79.png)
![screenshot02](https://user-images.githubusercontent.com/388198/55201537-b9d92880-51c3-11e9-99a0-28dc8479cbab.png)
![screenshot03](https://user-images.githubusercontent.com/388198/55201535-b9409200-51c3-11e9-9cc8-7abfe2e072de.png)

**Comment by mediaminister** [comment]
I get better quality with jpeg files. I used mozjpeg.
`cjpeg -quality 93 input.bmp > output.jpg`
[screenshots.zip](https://github.com/pietje666/plugin.video.vrt.nu/files/3026897/screenshots.zip)

**Comment by dagwieers** [comment]
The JPG sizes are indeed smaller, but they compress worse so the end-result for the ZIP file (for better quality images) is worse:

     -rw-rw-r--. 1 dag dag  58907 31 mrt 21:09 screenshot01.jpg
     -rw-rw-r--. 1 dag dag  95998 31 mrt 21:11 screenshot01.png
     -rw-rw-r--. 1 dag dag 163524 31 mrt 21:09 screenshot02.jpg
     -rw-rw-r--. 1 dag dag 186874 31 mrt 21:11 screenshot02.png
     -rw-rw-r--. 1 dag dag  81084 31 mrt 21:10 screenshot03.jpg
     -rw-rw-r--. 1 dag dag 104364 31 mrt 21:11 screenshot03.png

     -rw-rw-r--. 1 dag dag 290202 28 mrt 04:15 plugin.video.vrt.nu-1.7.1.zip          <-- No screenshots
     -rw-rw-r--. 1 dag dag 684180 29 mrt 01:39 plugin.video.vrt.nu-1.7.1-ce06cce.zip  <-- PNG (dithered)
     -rw-rw-r--. 1 dag dag 1062463 31 mrt 21:17 plugin.video.vrt.nu-1.7.1-46163a3.zip <-- JPG

**Comment by mediaminister** [comment]
Okay, png it is.
