### ISSUE TITLE
Date is not displayed for series that contain a single video

### ISSUE THREAD

**Issue by stevenvolckaert** [pietje666/plugin.video.vrt.nu#11]
For 'series' that contain just a single video, the date isn't displayed. Only the video title is shown.

I discovered this bug recently in `VRTPlayer.__get_single_video(path, soup)`, and I'll provide a fix shortly.

**Comment by pietje666** [comment]
I always thought you meant it  by design not to show the date when there was only one video.
I will wait ~1 month before merging to the kodi repo. Since the guys overthere do not like to merge all the time :).

**Comment by stevenvolckaert** [comment]
It's useful to show the release/publication date here too, in my opinion. After all, it can be seen on the VRT.NU website.

I agree it's better to wait a while before merging into the stable branch.

**Comment by pietje666** [comment]
Made a pull request for the kodi team with your changes
