### ISSUE TITLE
VRT.NU API offers only part of VRT websites?

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#127]
I noticed that on the Ketnet website it lists 52 Biba & Loeba episodes (complete Season 1's 39 episodes, and 13 Season 2 episodes). See URL below and click a few times on **Toon meer**:
- https://www.ketnet.be/kijken/biba-loeba

Through the VRT.NU API or website we only find 9 episodes:
- https://www.vrt.be/vrtnu/a-z/biba---loeba/2/biba---loeba-s2a2/
- https://vrtnu-api.vrt.be/search?i=video&facets[programUrl]=//www.vrt.be/vrtnu/a-z/biba---loeba/

**Comment by michaelarnauts** [comment]
Ketnet.be isn't part of the VRT.NU offering. It also contains small clips of shows (like een.be does) that aren't available on vrt.nu.

The vrt.nu Android app also shows only 9 episodes.

**Comment by dagwieers** [comment]
@michaelarnauts Sure, I was just wondering if this information would be accessible somewhere. As it ends up on the same object store the metadata could be somehow available in a different view as well.

**Comment by dagwieers** [comment]
I am moving this item to [the Ideas section of the Wiki](https://github.com/pietje666/plugin.video.vrt.nu/wiki/Ideas), we can still reopen this enhancement when someone is interested to work on this..
