### ISSUE TITLE
Follow categories or add Movies/Series to top menu

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#133]
I am still torn between doing this or not.

On one hand I think it will help a lot of people if both Movies and Series (and maybe News) would be in the top-level menu as these are the most popular categories people would return to.

On the other hand, at least for Series and other categories, a section with the stuff you have been following (like is shown on VRT.NU website) is a lot more convenient (but would require a login).

So maybe it does make sense for Movies (which people don't return to, but may make up the evening if you would consider watching a movie). To be discussed...

**Comment by pietje666** [comment]
I think keeping the functionality as close to vrt.nu is a good thing. Also its not that kodi is reacting slow right now moving through the menus takes almost no time

**Comment by dagwieers** [comment]
Closing this, we can come back to this if ever needed.

**Comment by dagwieers** [comment]
So we're back with some new ideas.

*The problem here is that people follow known series, and they can now track them. But they can't track movies or documentaries easily.*

For this I would like to implement one or all of the following:

- **Allow to 'follow' categories.**
  So if you would click 'Follow' on the category 'Documentaries' the add-on would automatically add all programs that you did not already follow from this category, on a daily basis. This would ensure that all documentaries will end up in "My most recent" and "My soon offline".

- **Allow to add categories to the "main menu" or "My programs"**
  The way you watch movies is different from watching series. For series you can follow them and list them easily, but for movies there's no mental process/flow that gets you to possible movies to watch. They do not appear easily, unless you go to Categories (which IMO no longer happens). So having the option to add specific categories into your "Main menu" or "My programs" would be a simple way to bring it into view when you are making a selection of what to view this evening.

**Comment by dagwieers** [comment]
While I still think being able to follow a category (and the plugin would then automatically follow new programs from this category that were not already followed), the newly added "My movies" and "My documentaries" fulfill my personal needs already. We can come back to this one at some other time.
