### ISSUE TITLE
Please add Channels list

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#15]
Retrospect has a channel list, it would be nice if one could select a program by channel name.

Why ?

Because you can add Ketnet and Ketnet Junior as favorites to for a separate Children user in Kodi, and they would go directly to all the children's section.

**Comment by pietje666** [comment]
Hi dagwieers, right now kodi vrt.nu addon is in maintenance mode. Features to be added are welcome but i will not program them myself. But i am glad to merge any pull request if i get them.
