### ISSUE TITLE
cannot enter @ sign user name

### ISSUE THREAD

**Issue by lebeno** [pietje666/plugin.video.vrt.nu#16]
Sorry if this is an issue related to Kodi, not the plugin, but when I want to enter the Username I cannot enter my e-mail address because the on-screen keyboard does not have any @ key. Even when plugging in a USB keyboard into my Rasberry Pi that runs Kodi, typing @ displays nothing in the Username field.

**Comment by lebeno** [comment]
Extra info, I tried with a physical USB keyboard and I can enter the @ sign when using the Alt key and the 2 key on an AZERTY keyboard. So workaround is using the Alt key, not the Alt Gr. So it looks this is a Kodi issue, not an issue with the plugin. Or does the plugin have influence on the type of keyboard that is being displayed? Or the type of field for the username?

**Comment by pietje666** [comment]
This is indeed a Kodi issue. Good that you found a solution! The addon does nothing for displaying the keyboard. As a matter in fact the whole settings page is made up by the standard kodi settings.xml file.
