### ISSUE TITLE
Lower quality stream/ ISP limits

### ISSUE THREAD

**Issue by vasonline** [pietje666/plugin.video.vrt.nu#172]
### Describe the bug ###

Might not be a bug with the addon...

Situation: went over download budget with ISP.
Download speed is now limited to ~100kB/s

Videostream from addon play for 2 sec, then buffers, then plays 2 sec.
Clearly the restricted bandwidth is playing a role here.
! no fault of the addon.

However VRT website does something different. When playing livestream
or using on demand it switches to a lower quality stream.
Playback then functions normal (no more buffer empty) at a lower quality.

I do not know, maybe the addon can implement something similar if it notices
the bandwidth is not sufficient?
A sort of auto fallback?

Greetings:

ps @dagwiers: Your EPG is great. MUCH better to use with the Kodi
remote.

**Comment by dagwieers** [comment]
@vasonline I will put it on the [Ideas](https://github.com/pietje666/plugin.video.vrt.nu/wiki/Ideas) Wiki page, but leave it to others to see if this is feasible (either by auto-sensing or by specifying a bandwidth limit).

**Comment by mediaminister** [comment]
You can also solve this issue immediately by changing ISPs. In my humble opinion, this is the best solution if you use internet streaming to watch VRT on your TV set.

This function is called "[adaptive bitrate switching](https://en.wikipedia.org/wiki/Adaptive_bitrate_streaming)" and this is not yet activated in [inputstream.adaptive](https://github.com/emilsvennesson/script.module.inputstreamhelper), the module Kodi uses for streaming. It will take some time to investigate en write code to get this working properly.

In the coming weeks I'll investigate how to implement a temporary fix with a user setting in our own addon.

**Comment by dagwieers** [comment]
Given the fact how well Kodi works on Android, being able to limit the bandwidth would be useful for using the VRT NU addon on mobile networks too.

**Comment by vasonline** [comment]
Hi,

@mediaminister: interesting read on link!
- Could be benefical too for a faster first load of the stream

@dagwiers:
Yes, mobile could a good reason too.

**Comment by mediaminister** [comment]
I have a first simple fix. When you disable the DRM setting in our add-on and disable the add-on inputstream.adaptive, you can use the Kodi bandwidth setting in System > Internet access > Internet connection bandwidth limitation again.
Pull request: https://github.com/pietje666/plugin.video.vrt.nu/pull/182
Zip:
[plugin.video.vrt.nu-1.8.0-fc47ace.zip](https://github.com/pietje666/plugin.video.vrt.nu/files/3144222/plugin.video.vrt.nu-1.8.0-fc47ace.zip)

**Comment by dagwieers** [comment]
@mediaminister It would be nice if our own HTTP code would adhere the bandwidth limitation as well (just as we could make inputstream.adaptive adhere to it too). But I would prefer if we would make stream selection something different from bandwidth limitation in the long run, as they play at different levels in the stack.

**Comment by mediaminister** [comment]
@vasoline: I found out inputstream.adaptive has also a bandwidth limitation setting in their add-on settings. So, it's possible to solve your problem by manually configuring a couple of settings.

So, while there is no automatic bitrate switching, you can do this manually.

@dagwieers Can you reconsider merging my pull request because automatic bitrate switching should be fixed upstream.

**Comment by dagwieers** [comment]
@vasonline We added 2 changes to the master branch that will affect your use-case positively. You can now set the max bandwidth the plugin should be using. Or you can set the global Kodi bandwidth limiting setting, both will affect our plugin (it will take the lowest limit of both settings).

Please test and report back ! ([Instructions to testing the master branch](https://github.com/pietje666/plugin.video.vrt.nu/wiki/Testing#test-the-master-branch-or-any-other-branch)

**Comment by dagwieers** [comment]
I added information related to these settings to our Wiki at: https://github.com/pietje666/plugin.video.vrt.nu/wiki/Bandwidth

**Comment by vasonline** [comment]
@Dagwiers:
Just went away a few days, and saw all the amazing work!

Will download the latest branch and test on our AndroidTV device.

**Comment by vasonline** [comment]
Update: works fine on our Android TV device.
Tested the different bandwidth settings and that worked perfectly.
You can easily see the different PQ quality on screen.

**Comment by dagwieers** [comment]
@vasonline Thanks for the feedback. Also thanks to @mediaminister to fix it for the HLS streams.
