### ISSUE TITLE
Dateutil on LibreELEC 8 (Kodi 17.6)

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#175]
### Describe the bug ###
@mediaminister [reported](https://github.com/pietje666/plugin.video.vrt.nu/issues/169#issuecomment-489134858) an issue with the **dateutil** module on LibreELEC 8.
No details yet.

### To Reproduce ###
1. Go to ...
2. Click on ....
3. Scroll down to ....

### Additional context ###

- Operating system: LibreELEC 8.2.5
- Kodi version: 17.6
- Addon version: 1.8.0

### Log (if available) ###
```paste below

```

**Comment by mediaminister** [comment]
Yesterday, I did a quick test of the urllib2 add-on update in a couple of virtual machines. When I ran [LibreELEC-Generic.x86_64-8.2.5.ova](http://archive.libreelec.tv/LibreELEC-Generic.x86_64-8.2.5.ova) in VMWare Workstation Player 15, the addon failed to install.
I'm not sure this is a real bug or there is something wrong with settings in [VMWare Workstation Player 15](https://www.vmware.com/be/products/workstation-player/workstation-player-evaluation.html)

Here are the relevant log lines:
```
18:06:59.374 T:139709921302272   ERROR: Copy - Failed write to file /storage/.kodi/addons/temp/97a28173-d55e-4f33-8cf7-0e015a7237cb/lib/dateutil/tz/tz.py
18:06:59.374 T:139709921302272   ERROR: Failed to unpack archive 'special://home/addons/packages/script.module.dateutil-2.7.3.zip' to '/storage/.kodi/addons/temp/97a28173-d55e-4f33-8cf7-0e015a7237cb'
18:06:59.375 T:139709921302272   ERROR: CAddonInstallJob[plugin.video.vrt.nu]: failed to install dependency script.module.dateutil
```
Complete log: http://ix.io/1HVC

**Comment by dagwieers** [comment]
From time to time I have seen installation errors for my own testbuilds, and a reboot of my system was required to install. The ZIP file was perfectly fine. The same exact error.

I wonder if there is a generic timing-sensitive bug somewhere?

**Comment by mediaminister** [comment]
The VRT NU add-on failed to install. After reboot there is no menu item. I'll look into this issue in detail at a later time.

**Comment by dagwieers** [comment]
In my case it was just our plugin that failed to install, as I already had the dependencies installed.

**Comment by dagwieers** [comment]
If this is in fact an general issue, v1.7 has the same issue and we haven't heard any complaints. So I don't see this as a showstopper anymore.

**Comment by dagwieers** [comment]
I am going to close this, please comment and reopen if you have an issue that may be related to this.

**Comment by mediaminister** [comment]
FYI: The bug was invalid. I increased storage in the Virtual Machine and the add-on just installs fine.

**Comment by dagwieers** [comment]
Thanks for confirming !
