### ISSUE TITLE
Restructure code

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#176]
### Describe the bug ###
A few thoughts on code structure:
- Kodi's included path for code is the main directory, not `resources/lib`
- We have issues because we include/import too much code that is unneeded
- A lot of functionality is locked inside classes, which complicate their use needlessly
- The current nesting of of classes/methods is too complicated
- Design should enable unit testing (so XBMC stuff should stay separated)

I would like to propose:
- Moving all code into a single directory (e.g; `./vrtnu/`) with potentially 10 to 15 files
- Use **script.module.routing** to improve addon entrance (see #103)
- Get rid of `actions.py` and the unwanted `__init__.py` files
- Separate files on function and reusability
- Import only needed data/classes/methods so it looks much cleaner to what is used
- Separate independent functions instead of static class methods (so they can be imported)
- Simplify TitleItem, or replace it with a well-designed dictionary

I am very skeptical to forced object oriented programming, it's nice where it improves readability, but sometimes putting stuff in classes together because you have to overcomplicates the design (and Python does not force you to).

**Comment by pietje666** [comment]
Maybe some static class methods could be replaced indeed. How do you mock stuff when using procedural  programming.
