### ISSUE TITLE
Yatse support

### ISSUE THREAD

**Issue by Joreel** [pietje666/plugin.video.vrt.nu#18]
Hey there!

I was wondering if it would be possible to add Yatse support to this plugin? With Youtube, TED and SoundCloud it is possible to send the video/music link from an Android phone through Yatse to Kodi. The video/music is then played on the TV.

What do you think? Would it be hard to implement this feature? If I wanted to do it myself, where should i start?

Great plugin by the way!

Thanks!

**Comment by pietje666** [comment]
Hi, my gues for a Yatse plugin is that you will first have to make a plugin for the yatse remote to begin with. More info to be found here https://yatse.tv/redmine/projects/yatse/knowledgebase/articles/22 (disclaimer, i never used yatse nor developed for it). When that is ready my addon should listen to yatse events some way and act on it (atleast that is what i think).

I do not know anything about your development skills, so its hard to judge. If you have zero programming experience it will be  very challenging

**Comment by Joreel** [comment]
I am a programmer myself, I wouldn't propose to do it if I wasn't. What I'm lacking now is time since I'm spending most of my time on my master thesis. I'll check out the link and see if I can do anything with it. I highly recommend using Yatse or Kore. It makes life easier, especially when you need to write text on the TV or when your remote's batteries died once more ...

Thanks for your response!

**Comment by dagwieers** [comment]
I once paid for Yatse, but since the release of the official Kore app, Kore serves all my needs.
You can even open the addon and browse the VRT.NU content through the Kore app and select what to play.
