### ISSUE TITLE
'Most Recent', but only of selected Favorites (Follow-support)

### ISSUE THREAD

**Issue by herwinc** [pietje666/plugin.video.vrt.nu#181]
### Describe the feature ###

The 'Most Recent' list is great. But it still has a lot of items I don't care for.
So, the option of showing this list with only items that I have selected (Favorites) and I am actually following.

The selection maybe can be done via vrt.nu ("programma's die ik volg") or -maybe better- in Kodi (Favorites) itself.

This way, when the user comes home from work, he or she is presented with a sort of daily TODO-list: You see a list of all episodes of your favourite (selected) programs. Sometimes you skip a couple of days of watching TV or you get back from a longer holiday, and in the same way, you are automatically presented with an a bit longer list and you can start binch-watching to get back up to date.

Thus, the Most Recent list of the things I am following. (This is truly interactive and customised TV)

Note that there is no need to have folders per program or so. Just a flat chronological list of a mix of episodes TODO.

This is better than having to remember to set up your Telenet-box, for them to still mess up the timing so you still miss the last 10 minutes of your program anyway, like it is a VHS and 1991.

**Comment by dagwieers** [comment]
@herwinc We have something like this on the [Ideas](https://github.com/pietje666/plugin.video.vrt.nu/wiki/Ideas) already, as a separate menu item. Although currently I don't know how to get to that list of favourites/watching series from the site. We can't use the Favourites functionality from Kodi, as this is more a bookmarks-utility.

But definitely something I am interested in having. The master branch already has quite some new functionality you may want to test. And we also accept contributions ;-)

**Comment by dagwieers** [comment]
Looking into this again, the VRT NU website no longer shows the "Recommended for you" section with the stuff I frequently watched. So if we want something like this, we actually have to create a context menu where people can "Follow/Unfollow" a program, and maybe also Settings item that lists the "Followed" programs.

Then we can have both a "A-Z" listing, as well as a "Recent" listing tailored to the user. I would probably put both in a single "My programs" main menu item. Please add any ideas / feedback here.

**Comment by herwinc** [comment]
Hello there,
Thanks for your reaction. Yes, that sounds great. 
My programs > A-Z would then be all episodes that are still online of all the selected programs? And the episodes grayed-out that that user has already watched. A flat list with long item names (Program name | episode title or number). Then yes, that would do it.
The only downside would maybe be that the user still has to go to the vrt.nu site (I never do that) to build the list. But if the follow/unfollow could be done from (or completely in) Kodi, that would be super.

That way, if you notice a new program eg in the normal A-Z or so, click Follow, and WHAM, the episodes are added to your custom list. Great stuff.

**Comment by dagwieers** [comment]
Ok, so I looked into how the website is doing this. Even though for me it is not working and I get an error when I click on "Volgen", the website is making this call with a specific payload:

- https://video-user-data.vrt.be/favorites/vrtnuazwinteruur

And to get an overview of what you have followed (your favorites) you can do this:

- https://video-user-data.vrt.be/favorites/

So the implementation is quite straightforward and I guess we can make a context-menu to follow/unfollow a program. And at the same time use this information to add a filter on our existing code. It's probably wise to cache this information locally and only refresh this information in a given (configurable) interval.

**Comment by dagwieers** [comment]
@herwinc Can you try out my implementation at #213 

You can install this file: https://github.com/dagwieers/plugin.video.vrt.nu/archive/favorites.zip
