### ISSUE TITLE
Some Kodi platforms don't localize day-of-week (TV Guide)

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#184]
### Describe the bug ###
There is a known issue with some Kodi platforms (i.e. LibreELEC) that do not ship a fully localized Linux OS. Because of this date strings (day of the week) is not properly translated into the native language. This looks weird in the TV Guide.

Possible fixes:
- Report upstream to get this fixed (unlikely, since LibreELEC is a "Just Enough OS" platform)
- Localize the day-of-week using Kodi language translations
- Localize the day-of-week through Kodi language translations in the plugin

This does not appear to be an issue on Windows or Android.

**Comment by dagwieers** [comment]
One strategy here could be to replace "%a" or "%A" (day-of-the-week) with internal strings.
Same could be done for "%b" and "%B" (month).

Honestly, I think Kodi should have a supporting call to do this automagically. (Added to the list)

**Comment by vasonline** [comment]
Hey,

Confirmed
I  observed this behavoir too in our AndroidTv box.
The Tv guide indeed has English titles.
