### ISSUE TITLE
Plugin fails on KodiLite

### ISSUE THREAD

**Issue by gmpinheads** [pietje666/plugin.video.vrt.nu#185]
sometime the plugin works in kodilite is it possible to fix it?

**Comment by gmpinheads** [comment]
I forgot the error:
 File "/usr/lib/enigma2/python/Plugins/Extensions/KodiLite/plugins/plugin.video.vrt.nu/default.py", line 30
    from __future__ import absolute_import, division, unicode_literals
SyntaxError: from __future__ imports must occur at the beginning of the file

Groeten Boris

**Comment by dagwieers** [comment]
We do not ship a default py, I can only assume KodiLite is modifying our code and causing this issue.

**Comment by gmpinheads** [comment]
ok i will try by myself

Op za 4 mei 2019 om 19:31 schreef Dag Wieers <notifications@github.com>:

**Comment by dagwieers** [comment]
@gmpinheads Let me know the details if you find what's going on.

**Comment by gmpinheads** [comment]
zal ik zeker doen

Op za 4 mei 2019 om 22:29 schreef Dag Wieers <notifications@github.com>:

**Comment by dagwieers** [comment]
Any feedback ? Otherwise I am going to close this.

**Comment by gmpinheads** [comment]
close it i comeback when i have more info

Op wo 8 mei 2019 om 11:38 schreef Dag Wieers <notifications@github.com>:

**Comment by dagwieers** [comment]
Can you close it ? I think that if I close it you can not reopen it.
(I don't know honestly, but I have seen this elsewhere ;-))
