### ISSUE TITLE
Logo update?

### ISSUE THREAD

**Issue by Joreel** [pietje666/plugin.video.vrt.nu#19]
Would you mind if we update the logo to one of these? They would look better on the TV next to the other logos like Auvio, Arte, TED, Youtube, SoundCloud ...

![image](https://user-images.githubusercontent.com/8089628/38379866-5a6d720a-3902-11e8-9ed1-91619e2d738b.png)

![image](https://user-images.githubusercontent.com/8089628/38379882-67b076b0-3902-11e8-9077-d2dd359e74cb.png)

**Comment by pietje666** [comment]
The reason i did not use the Vrt nu logo in the first place is because the original logo's contain a copyright. So i made the other logo and i actually like it.

**Comment by Joreel** [comment]
I understand, I didn't know about that.
