### ISSUE TITLE
Episode list does not load while using Yatse on Android

### ISSUE THREAD

**Issue by TASSDevon** [pietje666/plugin.video.vrt.nu#192]
### Describe the bug ###
Using Yatse, navigating the VRT NU addon menus, when e.g. going to het Journaal, the episode list is empty

### To Reproduce ###
1. Go to Android phone > Yatse app > Addons > VRT NU 
2. Click on het Journaal
3. See Yatse indicating that the list is empty

### Expected behavior ###
Previously (a few weeks ago) the list was populated with the episodes.

### Additional context ###
- Operating system: Android 9
- Kodi version: OSMC Easter Version (Kodi v18)
- Addon version: Latest
- Using a VPN: yes/no: no
- Country you are using the addon from: Belgium

### Log (if available) ###
Let me know if you need any logging from Kodi or could use adb to fetch from Yatse

**Comment by mediaminister** [comment]
Please @dagwieers don't introduce the same bug ever again! https://github.com/pietje666/plugin.video.vrt.nu/commit/f62e73c2a4072fe8f9e99bd591faa6bd8e8b4c0a#diff-f8ede559c7a7f78a75062fda8fa43219L206

**Comment by dagwieers** [comment]
Well, it was not the exact same bug :-) But yeah, we did some experimenting with metadata (infoLabels) and none of them are properly documented what they are meant for or how they affect Kodi. Or if that documentation exists, I have not seen it.

But at least it brought me to studio icons by accident, so I am regretting I did that :-)

**Comment by dagwieers** [comment]
Maybe we can release v1.9.1 with the recent features + fixes ? My v1.9.0 has still not been accepted to the repo :-(

**Comment by TASSDevon** [comment]
Yatse dev's reply here: https://community.yatse.tv/t/episode-list-of-vrt-nu-addon-not-loading-in-yatse/1759/3

**Comment by dagwieers** [comment]
@TASSDevon It should be fixed by @mediaminister in the master branch. Please try the latest devel branch [as explained on the Wiki](https://github.com/pietje666/plugin.video.vrt.nu/wiki/Testing#test-the-master-branch-or-any-other-branch). We may release a v1.9.1 with this fix included, but it is still unclear when.
