### ISSUE TITLE
List videos of multiple seasons if there's more than a single season

### ISSUE THREAD

**Issue by stevenvolckaert** [pietje666/plugin.video.vrt.nu#2]
I noticed today that series which have multiple seasons, only the episodes of a single season is listed (the least recent one, it seems).

For example, selecting the [Tomtesterom][1] series from the the **A-Z** or **Categories** view, only shows the episode of season 2, while there's also an episode in season 3 (as of today, June 24, 2017).

[1]: https://www.vrt.be/vrtnu/a-z/tomtesterom/2/tomtesterom-s2a6-marathon-des-sables/

**Comment by pietje666** [comment]
Just checked it on the vrt.nu site. Do you know if this is new behaviour from vrt.nu i did not see it in the passed thanks for noticing it!

**Comment by stevenvolckaert** [comment]
Not sure whether this is new behavior, but I wouldn't be surprised if it is.

I used @timdp's [De Redactie][1] Kodi add-on before, but it stopped working recently. It was then that I discovered your VRT NU add-on, which of course offers much more content.

[1]: https://github.com/timdp/plugin.video.deredactie
