### ISSUE TITLE
Add Ketnet Junior stream

### ISSUE THREAD

**Issue by michaelarnauts** [pietje666/plugin.video.vrt.nu#207]
For young children, Ketnet Junior can also be added as a live stream. They are using `https://content.uplynk.com/channel/e11a05356cc44198977436418ad71832.m3u8` for a few months now already, so it seems quite stable. They provide a nice 720p stream, no login required.

**Comment by dagwieers** [comment]
But Ketnet Junior is broadcasted on Canvas already.

**Comment by michaelarnauts** [comment]
Sure, but only in the afternoon and when there is no other broadcast going on (live sports for example). The live stream is 24/7.

**Comment by dagwieers** [comment]
I didn't know they had a different schedule for 24/7. Is this also what you get if you have a digital TV subscription ? Even Ketnet does not have a 24/7 schedule.

**Comment by michaelarnauts** [comment]
I think Canvas just taps into that 24/7 livestream when it broadcasts (today for example, there is no Ketnet Junior). It doesn't have a schedule afaik.

I don't have a digital tv subscription, but I guess you can also tune in to this same 24/7 stream when you press the red button on Ketnet.

**Comment by dagwieers** [comment]
It is unfortunate that this link is not available using the same mechanism as all the others :-/
Thanks, I will look at the best way to integrate it. Possibly scraping with a fallback mechanism.

**Comment by michaelarnauts** [comment]
Not sure you need to scrape it. I haven't seen that the url changed since I'm using it (over a few months). I guess you can just add an item to the live streams and pass Kodi this url? (not sure about the internals of Kodi, but I guess you can just feed it a url to a HLS stream and it will handle it itself?)

**Comment by dagwieers** [comment]
@michaelarnauts We do this already for all other TV channels since v1.8.0. Try scraping, if it fails use another mechanism. If that fails I would go for a hardcoded URL. We have unit tests for this now, so we know when scraping fails without impacting the end-users. Resilience over everything, we learned :-)

**Comment by michaelarnauts** [comment]
Sure, but can't we use the URL, and only scrape if that fails? Will help a lot on slower rpi's! The same for the normal een, canvas and ketnet streams. It's not that they change regularly...

**Comment by dagwieers** [comment]
@michaelarnauts We do that for the other mechanism (as we can detect that the mechanism failed), but we cannot do that in this case. In fact my current implementation only uses the URL as I don't have a working web scraper yet, but we would have to change the logic too for this.

If you are interested to learn how it works, be my guest to go through the code ;-)

**Comment by dagwieers** [comment]
> Today for example, there is no Ketnet Junior (on Canvas)

Last night something weird happened for the live streams, during the night (not sure when it started) all live streams were either blue or light blue. Even the Radio streams. And the Sporza stream used to show a black screen but it was also light blue. I think it was the Ketnet stream that showed and old colorful test-screen (like we used to get in the eighties !).

Now today the Sporza stream again shows the still image that the stream has (temporarily?) finished.
(In 720p even ! :-)) So they fixed that when they fixed the live streams this morning.
