### ISSUE TITLE
Don't cache show listings

### ISSUE THREAD

**Issue by michaelarnauts** [pietje666/plugin.video.vrt.nu#210]
### Describe the bug ###

I have added shortcuts to some programs from the A-Z listing in Kodi. This makes it easy for the kids to start watching "Karrewiet", since they can just open it trough the favourites. They watch the latest episode every day, and go back to the main menu then. When they want to view the next episode the next day, they open "Karrewiet" again, but the listing doesn't refresh and the newest episode isn't visible. Going back and opening it again doesn't solve this.

A workaround is to add a different show, open that one, and then go back to karrewiet, but my kids say that's stupid :)

### To Reproduce ###
1. Add a show from the A-Z listing to favorites (context menu, add to favourites)
2. Go to the favourites and open the show.
3. Play something, or not, not important.
4. Go back to the main menu.
5. Time passes, a new episode has aired.
6. Go to favorites and open the show.
7. The old listing is displayed and no way to refresh is available.

### Expected behavior ###
When the show is opened, it should download the listing again.

### Additional context ###
- Operating system: OSMC
- Kodi version: 18
- Addon version: latest master
- Using a VPN: no
- Country you are using the addon from: Belgium

### Log (if available) ###
```paste below
N/A
```

**Comment by dagwieers** [comment]
As we  discussed, I think an option in **Settings - VRT NU** » **Interface** » **Cache menu listings** is in order to influence menu caching. By default it would be enabled, but you can disable it for your use case.

**Comment by dagwieers** [comment]
We added **Refresh** to the context menu, so in case you need to you can easily refresh every menu.
