### ISSUE TITLE
auto-login using .netrc credentials

### ISSUE THREAD

**Issue by sharethewisdom** [pietje666/plugin.video.vrt.nu#214]
Could the [.netrc file](https://www.gnu.org/software/inetutils/manual/html_node/The-_002enetrc-file.html) be used as a source of credentials for automatically logging in?

**Comment by dagwieers** [comment]
That is an atypical request for a Kodu plugin, why would that be useful? Currently the policy for official plugins is that they don't read/write files outside its own addon userdata directory.

**Comment by sharethewisdom** [comment]
To be honest I've never used Kodu. Do plugins store cookies? I assumed logging in was necessary  every so often. Anyway, I like the convenience of youtube-dl [logging vrtnu in for me](https://github.com/ytdl-org/youtube-dl/blob/e6a25fea23c4ee1db2461e77b457d01dc922a0a6/youtube_dl/extractor/canvas.py#L178), and I thought others might find it useful as well. Also, python is used there as well. Would it be hard to refactor?

**Comment by dagwieers** [comment]
I don't understand your request if your not even using Kodi.
