### ISSUE TITLE
More than 150 episodes get truncated

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#227]
### Describe the bug ###
In case there are more than 150 episodes available, the list is truncated.
https://vrtnu-api.vrt.be/search?i=video&facets[programUrl]=//www.vrt.be/vrtnu/a-z/winteruur/&size=150

We ought to keep on getting the remaining pages until we have everything.

**Comment by dagwieers** [comment]
In practice this isn't an issue as the facets-summary lists all season + episode counts.
But our new code would take a random episode from the season for the thumbnail, and this fails.

**Comment by mediaminister** [comment]
So we need to make at least 3 requests to the api, just to get a random thumbnail for the Winteruur season listitem? That is exaggerated.

I don't see the added value of the (* All seasons) menu item. This mixes up episodes that don't have anything in common. Sorting and item naming is also not adapted in this menu. The current implementation is useless.

Why should we have one list mixing up Season 22 and Season 24 of Thuis for example? There are completely different characters and story lines. VRT NU doesn't provide such a list on their website and other streaming sites like Netflix or VTM GO don't provide this functionality either.

I want to fix this bug, but the random thumbnail function and (* All seasons) menu makes it unnecessarily complicated.

**Comment by dagwieers** [comment]
> So we need to make at least 3 requests to the api, just to get a random thumbnail for the Winteruur season listitem? That is exaggerated.

yeah, that makes no sense, and that's not what I think needs fixing.

> I don't see the added value of the (* All seasons) menu item. This mixes up episodes that don't have anything in common. Sorting and item naming is also not adapted in this menu. The current implementation is useless.

I think it is useful. Especially for e.g. Nachtwacht where they release 2 or 3 episodes, but you don't know in what Season the new one is listed and you may have to look in 3 folders before you know what you can choose between.

> Why should we have one list mixing up Season 22 and Season 24 of Thuis for example? There are completely different characters and story lines. VRT NU doesn't provide such a list on their website and other streaming sites like Netflix or VTM GO don't provide this functionality either.

For Thuis it (currently) does not make sense. On the other hand, you don't have to enable it. Maybe changing the sort-order for this view to episode makes more sense. I'll look into that.

But just like the current season-splitting is not optimal for some series, the *&ast; All seasons* view is not optimal for others. A more sensible displayOptions coming from VRT would be better.


> I want to fix this bug, but the random thumbnail function and (* All seasons) menu makes it unnecessarily complicated.

Well, there's nothing to fix if you would remove the *&ast; All seasons* option IMO.

**Comment by mediaminister** [comment]
Thanks for the explanation, in the meantime I fixed this bug in https://github.com/pietje666/plugin.video.vrt.nu/pull/260
