### ISSUE TITLE
geen vrt Nu

### ISSUE THREAD

**Issue by twinkels** [pietje666/plugin.video.vrt.nu#23]
VRT NU werkt op dit moment niet  de live uitzendingen

**Comment by pietje666** [comment]
Blijkbaar werken afleveringen met slechts 1 aflevering niet. Livestreams werken wel ik denk dat je dat bedoelt?

**Comment by twinkels** [comment]
VRT NU werkt op dit moment niet de live uitzendingen nog steeds niet???

**Comment by twinkels** [comment]
Wil gewoon live kijken naar de programma VRT EEN en CANVAS

**Comment by pietje666** [comment]
Live streams horen gewoon te werken als je versie hoger is dan 1.2.0 . Net getest en werkt bij mij gewoon. Daarvoor waren er inderdaad problemen met de livestreams.

**Comment by dagwieers** [comment]
@twinkels Het is moeilijk om te helpen als je zinnen onduidelijk zijn. Probeer eens correcte Nederlandse volzinnen te gebruiken. Misschien dat ik dan ook iets zinnigs kan terugzeggen.

Alleszins werken de livestreams voor mij perfect in de Kodi addon. Ik gebruik de allerlaatste .zip file (v1.3.1).

PS @pietje666 Het zou wel handig zijn moesten er echte releases gemaakt worden, zodat er hier ZIP files stonden: https://github.com/pietje666/plugin.video.vrt.nu/releases

**Comment by pietje666** [comment]
@twinkels  ik denk dat je fout zit en je de vrt.nu website bedoelt. Deze pagina gaat enkel over de niet officiële Kodi addon. Voor zaken van vrt.nu zelf kan je hier eens horen => https://www.facebook.com/vrtnu/ 

@dagwieers Done ;)

**Comment by dagwieers** [comment]
@pietje666 You rock ! Dat maakt het eenvoudiger om te testen. En nu kan ik anderen meteen daarheen sturen. Bedankt !
