### ISSUE TITLE
Programs in TV guide no longer plays video

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#238]
### Describe the bug ###
I don't understand why, but it seems programs in the TV guide no longer can be played.

@mediaminister As you understand better how this mechanism works, can you investigate ?

**Comment by mediaminister** [comment]
I'll look into it.

**Comment by dagwieers** [comment]
I found the cause from #208: https://github.com/pietje666/plugin.video.vrt.nu/pull/208/files#diff-3068a65f7c424ae8246eb6d861867028R192

Not sure what the best way is to fix this.

**Comment by mediaminister** [comment]
I have an updated streamservice ready that fixes this: https://github.com/pietje666/plugin.video.vrt.nu/pull/243
