### ISSUE TITLE
Aflevering van reeks verschijnt soms niet in de lijst

### ISSUE THREAD

**Issue by pdedecker** [pietje666/plugin.video.vrt.nu#24]
Eerst en vooral: bedankt voor de add-on. Wij zijn grote fan!

**Describe the bug**
Een aflevering uit een reeks verschijnt soms niet in de lijst in de VRT Nu add-on.

Voorbeeld: "Iedereen beroemd" op https://www.vrt.be/vrtnu/a-z/iedereen-beroemd/2018/iedereen-beroemd-d20180714/. De website toont als meest recente aflevering die van 14/7, maar op Kodi verschijnt deze aflevering niet (meest recente aflevering in de VRT Nu add-on is die van 13/7).

Een ander voorbeeld uit de programma's die VRT Nu momenteel aanprijst op haar home pagina: bij "Flikken" zie ik 13 afleveringen op https://www.vrt.be/vrtnu/a-z/flikken/2002/flikken-s2002a1-vluchtmisdrijf/, maar de VRT Nu add-on toont er 12 ("Vluchtmisdrijf" ontbreekt).

**Desktop (please complete the following information):**
Kodi 17.3 / LibreElec op RPi 2
VRT Nu 1.3.1

**Comment by pietje666** [comment]
Fixed in version 1.3.2, pushed new version thx for reporting the Bug!
