### ISSUE TITLE
Kore remote control does not support formatting in labels

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#249]
### Describe the bug ###
The Kore remote control app for Android does not support text formatting in labels.

Since we added [B] (bold) to "Most recent" listing, Kore shows these tags as-is.

We need to report/fix this upstream.

**Comment by dagwieers** [comment]
Relates issues:
- https://github.com/xbmc/Kore/issues/629
- https://github.com/xbmc/Kore/issues/426

**Comment by dagwieers** [comment]
The Yatse remote control app is not affected by this issue.

**Comment by dagwieers** [comment]
I believe this will be fixed if xbmc/Kore#667 is merged.

**Comment by mediaminister** [comment]
It is merged.

**Comment by dagwieers** [comment]
Indeed, waiting for it to become released though, so we can finally close this.

**Comment by dagwieers** [comment]
I tested the latest beta version of Kore, and unfortunately the title-formatting is not being stripped. So the VRT NU interface still doesn't look very nice in Kore :-( In Yatse things do look nice though.

**Comment by SyncedSynapse** [comment]
xbmc/Kore#688 should fix it

**Comment by dagwieers** [comment]
@SyncedSynapse This is indeed now fixed. There is a small issue that for the thumbnails it is still taking the first character **[** rather than the first character of the sanitized title, but that's just a minor detail.

A working version is available from: http://mirrors.kodi.tv/tools/kore/nightlies/

**Comment by dagwieers** [comment]
So the latest update on Android got the fixes in. We can close this tracking issue.
