### ISSUE TITLE
Soon offline menu

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#252]
### Describe the feature ###
I found that we can list content by date when it is removed.

- https://search.vrt.be/search?size=150&facets[assetOffTime]=2019-05-17

This opens up the possibility list items that will disappear soon. We can have the same list filtered by programName for the "My programs" section. We can also list multiple dates:

- https://search.vrt.be/search?size=150&facets[assetOffTime]=[2019-05-18,2019-05-19]&order=asc

The order will list programs based on broadcast date by default (newest first), or ascending (oldest first). If you list more than one date, it will sort first by date of removal, and then by broadcast date (which is highly inconvenient for us).

**Comment by dagwieers** [comment]
I struggle with a good name for this feature, another addon calls this list **Soon offline**.

**Comment by michaelarnauts** [comment]
@dagwieers the dutch "binnenkort verwijderd" sounds a bit strange. What about something like "Laatste kans" / "Last chance".

In the VRT NU mailing, they also use "Laatste kans" when a show is almost gone.

**Comment by dagwieers** [comment]
@michaelarnauts I am undecided. It means that in "Mijn programs" it will become "Mijn laatste kans" which sounds very doomsday-like :-) The deadline for the name is just-before-the-new-release !

**Comment by michaelarnauts** [comment]
![image](https://user-images.githubusercontent.com/1193779/57973609-de73a480-79ab-11e9-8863-555ceac2c217.png)
:)
