### ISSUE TITLE
Fail to start serie, for example: Escape to the chateau

### ISSUE THREAD

**Issue by JeanPoll** [pietje666/plugin.video.vrt.nu#26]
When I try to play for example: _Escape to the chateau_ it does not start.
Most other content works to play:

_21:47:03.622 T:1405088512  NOTICE: Creating Demuxer
21:47:07.243 T:1405088512   ERROR: OpenDemuxStream - Error creating demuxer
21:47:07.243 T:1405088512  NOTICE: CVideoPlayer::OnExit()
21:47:07.253 T:1926162944   ERROR: Playlist Player: skipping unplayable item: 0,                                                                                                        path [plugin://plugin.video.vrt.nu/?action=play&video=%2Fvrtnu%2Fa-z%2Fescape-t                                                                                                       o-the-chateau%2F2%2Fescape-to-the-chateau-s2a3%2F]
21:47:07.275 T:1926162944  NOTICE: CVideoPlayer::CloseFile()
21:47:07.275 T:1926162944  NOTICE: VideoPlayer: waiting for threads to exit
21:47:07.275 T:1926162944  NOTICE: VideoPlayer: finished waiting
21:47:07.275 T:1926162944  NOTICE: CVideoPlayer::CloseFile()
21:47:07.275 T:1926162944  NOTICE: VideoPlayer: waiting for threads to exit
21:47:07.275 T:1926162944  NOTICE: VideoPlayer: finished waiting_

The serie does work when I play it from te vrt nu website.

**Comment by pietje666** [comment]
Fixed in version 1.3.3 making a version as we speak!
Thanks for reporting the issue!

**Comment by JeanPoll** [comment]
Thx a lot
