### ISSUE TITLE
TV guide crashes after selecting the date from a month ago

### ISSUE THREAD

**Issue by mediaminister** [pietje666/plugin.video.vrt.nu#263]
### Describe the bug ###

TV guide crashes after selecting the date from a month ago: when you select the very last date item in the TV Guide, the schedule won't show up but you get a VRT NU error

### To Reproduce ###
1. Go to TV Guide ==> scroll down to the very last item
2. Click on the date from one month ago and click Eén, Canvas or Ketnet
3. See error: VRT NU error, check the log for more information

### Expected behavior ###
When clicking a channel, a schedule of the programs of the selected date should show up.

### Additional context ###

- Operating system: Linux Mint
- Kodi version: Kodi 18.2
- Addon version: master branch
- Using a VPN: no
- Country you are using the addon from: Belgium

### Log (if available) ###
```paste below
2019-05-21 20:57:56.690 T:140069303408384   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'O8'
                                            Traceback (most recent call last):
                                              File "/home/.kodi/addons/plugin.video.vrt.nu/addon.py", line 94, in <module>
                                                router(sys.argv[2][1:])
                                              File "/home/.kodi/addons/plugin.video.vrt.nu/addon.py", line 43, in router
                                                _tvguide.show_tvguide(params)
                                              File "/home/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer/tvguide.py", line 57, in show_tvguide
                                                episode_items = self.show_episodes(date, channel)
                                              File "/home/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer/tvguide.py", line 145, in show_episodes
                                                episodes = schedule[channel.get('id')]
                                            KeyError: u'O8'
                                            -->End of Python script error report<--
```

**Comment by mediaminister** [comment]
I noticed another problem related to this issue: all other date items that aren't yesterday, today or tomorrow show the schedule of the previous day.

**Comment by dagwieers** [comment]
Ouch, that should have been easy to verify from the logs (see what file was downloaded).
I wonder if we shipped it like this in v1.9.0 ? Can't check now, will check later.

**Comment by mediaminister** [comment]
Checked it, in 1.9.0 everything is fine.

**Comment by dagwieers** [comment]
I've been improving the unit tests (that I can do now) and there it seems to work as well.
It looks as if it is downloading the correct file for viewing?

**Comment by dagwieers** [comment]
Ah, I found it. The problem is in the listing, not the conversion.

**Comment by dagwieers** [comment]
The off-by-one issue is related to the fact that we take the previous schedule if it is before 6AM. For the last entry that is a problem because it has already disappeared. So for keeping this simple, I just added one item less to that list (even though it would work 18 hours a day ;-)

**Comment by mediaminister** [comment]
We should never take the previous schedule. If the user selects Sunday, he always should get programs of Sunday.
I don't understand your logic here.

**Comment by michaelarnauts** [comment]
You might want that if a show starts at 23:00 and ends at 2:00 for example. You might want to display that show also on the next day.

**Comment by mediaminister** [comment]
I understand, but this is not common for TV guides. Implementing this in a good way is more complicated. We should then take two day schedules and combine the relevant items into a new day schedule that covers 24 hours.

**Comment by dagwieers** [comment]
> We should never take the previous schedule. If the user selects Sunday, he should always get the Sunday programs. I don't understand your logic here.

Almost all TV guides do it like this. And it is most convenient.
- https://www.vrt.be/vrtnu/tv-gids/
- https://www.nieuwsblad.be/tv-gids
- https://www.demorgen.be/tv-gids/een/
- https://www.q2.be/tv-gids
- https://vtm.be/tv-gids
- http://www.mtv.be/tv-gids
- http://www.nickelodeon.be/tv-gids
- https://www.zestv.be/tv-gids
- https://www.foxtv.be/tv-gids/fox

**Comment by mediaminister** [comment]
I think there is a misunderstanding here. If the user clicks **Wednesday May 22**, we should always get https://www.vrt.be/bin/epg/schedule.2019-05-22.json and never https://www.vrt.be/bin/epg/schedule.2019-05-21.json

**Comment by dagwieers** [comment]
I disagree. A "broadcasting day" runs from 6AM until 6AM (in some cases from 5AM until 5AM).
So if you ask "today's" schedule at 1 AM, you expect to see "yesterday's" schedule.

We can argue if this should also affect other dates, but if you do this only for today, yesterday or tomorrow, it messes up everything.

**Comment by michaelarnauts** [comment]
Hmm. I tend to agree with mediaminister here. I expect to find airings on the day it is aired. Even during the night. With an exception for shows that cross midnight, I expect them to be in both days.

**Comment by dagwieers** [comment]
Alright, I accept a PR that can merge schedules.

**Comment by mediaminister** [comment]
Okay, this will take time as it not easy to do this the right way.

**Comment by dagwieers** [comment]
BTW I don't think your depiction of how it works is correct. The TV guide overview of dates simple shows "Today" as the previous day until after 6AM. We always show the schedule of the day that is selected IMO (except that there was a bug that we did fix).

**Comment by dagwieers** [comment]
And there was another issue where clicking on today, tomorrow and yesterday did not bring you to the advertised date (between 12AM and 6AM).
