### ISSUE TITLE
Prepare for release v1.10.0

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#266]
### Describe the feature ###
Now that v1.10.0 is feature complete (ignoring that one known tvguide issue), what is required to release this ?

From the original list of ideas, and accumulated new ideas. There is almost nothing left.
https://github.com/pietje666/plugin.video.vrt.nu/wiki/Ideas

**Comment by mediaminister** [comment]
Code is written, so now we have to test this until the end of May?

**Comment by dagwieers** [comment]
I have one open topic related to naming. What's the best name:
- Soon offline  //  My soon offline
- Last chance  //  My last chance

And in Dutch:
- Binnenkort verwijderd // Mijn binnenkort verwijderd
- Laatste kans  //  Mijn laatste kans

PS The names in Dutch and English don't have to be exact translations...

**Comment by mediaminister** [comment]
Offline is also a well established term in Dutch
So: Soon offline ==> Binnenkort offline

I don't like "last chance" because it's not a neutral term. Sounds intimidating.

**Comment by dagwieers** [comment]
I also wanted to restructure our code a bit.
- Get rid of the directory structure
- Move some classes together in a single module
- Better separate generic functions and class methods
- Only import the stuff we are actually using from modules.
- Add docstrings to all functions/classes

But this can wait.

**Comment by dagwieers** [comment]
We may want to update the screenshots as the previous set of screenshots no longer resemble the current add-on.

**Comment by mediaminister** [comment]
I get a HTTP Error 401: Unauthorized with `_get_fav_xvrttoken` in Kodi 17.3 and no time right now to investigate.
So please wait with a release.
Also `setSetting` in unit tests is missing

**Comment by dagwieers** [comment]
I do not plan to release before 01/06, we said we'd wait one more week for testing.
And if needed extend it. There is no need to rush anything.

**Comment by mediaminister** [comment]
Is the Channels menu broken?

**Comment by dagwieers** [comment]
@mediaminister I tried installing LibreELEC 8 and 7 in VirtualBox, but it appears the VirtualBox graphics driver is not supported by LibreELEC. Couldn't find any other JeOS with Kodi for running inside a VM, so for the time being I will not be testing with Kodi Krypton :-/

**Comment by mediaminister** [comment]
You need VMware Workstation Player, free for non-commercial use: https://www.vmware.com/be/products/workstation-player/workstation-player-evaluation.html

You can just import the ova files from http://archive.libreelec.tv
For the VRT NU add-on you need to expand the VM disk capacity, otherwise installing some dependencies will fail

**Comment by dagwieers** [comment]
Yeah, I don't want to install VMware on my system as well. I'd rather not have both VMware and VirtualBox nesting in one kernel :-)

**Comment by mediaminister** [comment]
No problem, I tested this already and I can confirm the master branch works fine on Kodi Krypton.

**Comment by dagwieers** [comment]
You tell me when we are ready to release.
It's a long weekend, maybe we should take advantage of that? ;-)

**Comment by mediaminister** [comment]
Still testing ;-)

**Comment by dagwieers** [comment]
PS I have seen another issue (and this was also reported on Facebook) but I don't think we can do anything about it.

Sometimes a stream suddenly stops. And opening it again may not offer to start where it stopped. This was seen in the "Most recent" menu, but I think it can happen for every (recent) stream.

My feeling is that at the VRT they have modified and replaced the original stream (and possibly removed the existing stream too soon). I have seen that from time to time streams that are still being broadcasted live, or that are incorrectly cut exist, and after some time have been replaced.

Not sure if you ever experienced this. The log doesn't really show anything wrong (but I don't have Kodi debug logging on).

**Comment by mediaminister** [comment]
I know, this bug occurs when VRT serves VOD-programs from a livestream with the so called "virtual subclips": http://docs.unified-streaming.com/documentation/vod/player-urls.html#virtual-subclips

But there is a problem  with VRT's implementation of this "Live to VOD" functionality. VRT doesn't provide an ending timestamp when a live broadcasted program is not yet finished.

I tried to fix this with `_fix_virtualsubclip'. This function ensures that the stream starts from the beginning of the program by adding an ending timestamp to the URL, but there is a problem with future ending timestamps. It seems I can only use past ending timestamps. So, these programs don't play till the end.

I should investigate this further, but I suspect there is something wrong with the HLS and MPEG_DASH manifest files VRT provides.

**Comment by dagwieers** [comment]
@mediaminister Could you open an issue for this? So it is clear to users it is known and we plan to fix this. Thanks!

**Comment by mediaminister** [comment]
Still one bug:
> I get a HTTP Error 401: Unauthorized with _get_fav_xvrttoken

I encountered the bug a couple of times on Kodi 17 and Kodi 18.

This bug occurs sometimes when selecting a VOD-program and logging in for the first time. In that case `streamservice` and `favorites` are requesting their own xvrttoken at the same time.

I'm trying to fix this before June 1

**Comment by mediaminister** [comment]
The HTTP Error 401 bug is invalid. I found the cause:
If Kodi system time is set incorrectly (for instance in my LibreELEC testing VM's), cookielib thinks cookies are expired and doesn't send them back to the server and login fails.

So everything works fine as long as the Kodi system time is set correctly.
I didn't find any other bugs (yet), I just found a couple of typos in the last commit: https://github.com/pietje666/plugin.video.vrt.nu/pull/283

**Comment by dagwieers** [comment]
We may want to add this information somewhere in the documentation. Another option is to compare system time with e.g. the VRT HTTP server and warn if out of range. We could do this when we e.g. get a non-200 error. And report back.

https://daniel-lange.com/archives/37-httpdate-set-local-date-and-time-from-a-web-server.html

**Comment by mediaminister** [comment]
I don't think it's necessary to write code for this very infrequent problem. I could only reproduce the problem on a freshly booted LibreELEC image in VMWare. After a reboot the problem disappeared.

I added some information for "Regional" settings to the wiki to inform users that setting date ande time correctly is important to have a well functioning add-on: https://github.com/pietje666/plugin.video.vrt.nu/wiki/Kodi-settings#regional

**Comment by dagwieers** [comment]
Ok, I will prepare the v1.10.0 release. Since it took more than a week last time, we may still have time to fix anything that comes up in that window. Or instead it might get released right away :-D
