### ISSUE TITLE
Some Items wont play

### ISSUE THREAD

**Issue by pietje666** [pietje666/plugin.video.vrt.nu#27]
**Describe the bug**
Some items wont play for instance Dagelijkse Kost. When looking in the log we can see that he url to play the items is different then usual. It starts with "Remix" => http://remix.aka.vrtcdn.be/remix/121c2b8e-6369-441b-8efa-d3cd6c79e744/remix.ism/.m3u8

**To Reproduce**
1.Select  A-Z
2. Select Dagelijkse Kost
3. Select the first item
4. Application gives loading screen but does not play the item

**Expected behavior**
The item should be played

**(please complete the following information):**
 - Operating system: Libreelec
 - Kodi Version: 17.6

**Additional context**
- Using a VPN: No
- Country you are using the addon from: BE

**Comment by dagwieers** [comment]
On my system remix.aka.vrtcdn.be does not even resolve. However remix-aka.vrtcdn.be does resolve, but the IP addresses don't work if I spoof those for remix.aka.vrtcdn.be :-(

What is weird is that for a single show, one episode worked last week fine, but today it not longer works (much like the other episodes). (In this case the show was De Ideale Wereld).

**Comment by dagwieers** [comment]
So my dirty fix works, no spoofing DNS, but rewriting the URL.

**Comment by pietje666** [comment]
Perfect, thanks will merge somewhere this weekend

**Comment by dagwieers** [comment]
Maybe I should have left a small comment so we know this may be temporary ?
I assume somewhere there's a bug at the VRT which is still exposing an (old?) domain to the outside world ?

**Comment by dagwieers** [comment]
@pietje666 Sure, this was a quick hack to make it work. I would do this differently myself if I had known it was going to be accepted ;-) Thanks for your dedication !
