### ISSUE TITLE
Visual Studio files no longer maintained

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#279]
### Describe the bug ###
I just noticed that the *plugin.video.vrt.nu.pyproj* file has gone stale, and I wonder whether we should continue to ship it.

I could update and add the missing/moved files, but I don't know what the purpose and relevance is of this file.

**Comment by dagwieers** [comment]
@pietje666 Is it a problem if it no longer consists of the correct filenames?

**Comment by pietje666** [comment]
no it is ok, file can be removed if i work on it i will just create a new project file myself

**Comment by dagwieers** [comment]
We can add them to .gitignore so they are local only ?

**Comment by pietje666** [comment]
for now ill just remove them manually so i can still push them to my own branches
