### ISSUE TITLE
Subtitles (TXT 888) for the hearing impaired?

### ISSUE THREAD

**Issue by vasonline** [pietje666/plugin.video.vrt.nu#33]
Hi,

I tried the vrt.nu plugin. Works great! Many thanks!
Can it be possible there are no subtitles for the hearing impaired?
It can a big issue for the people that are older/hearing impaired.
Would you want to add it in a future update?
Maybe I overlooked it, and it's already added? I clicked on the subtitle icon when playing the
livestream of één during the VRTnews. Got no subtitles.

Greeting and thanks!

**Comment by pietje666** [comment]
Actually this was working before, but then at vrt they changed something and subtitle url was always empty . The setting is still available as addon setting but non functioning. Might research in the future if i can get it working again

**Comment by vasonline** [comment]
Hi pietje666,

Thanks for the reply!
Would be great if you (or others) could get working before the DVB-T switchoff.
It can be a really needed feature for the hearing impared!
I think we need an open VRT.nu API

Greetings.

**Comment by mediaminister** [comment]
The HLS-stream contains fragmented WebVTT subtitling and this is not yet supported by inputstream.adaptive: https://github.com/peak3d/inputstream.adaptive/issues/183

But, the MPEG DASH-stream contains TTML subtitling and this is supported by inputstream.adaptive. A possible fix is to select the MPEG DASH-stream instead of the HLS-stream.

In my pull request I added support for the DRM-protected livestreams, which are MPEG DASH-streams. So subtitling will work at least for the livestreams if you have Kodi 18 with inputstream.adaptive and libwidevinecdm.

**Comment by vasonline** [comment]
Hi mediaminister!

Thanks for the extensive lookup!
So we might have a two ways to fix this issue.

Greetings

**Comment by vasonline** [comment]
Hi mediaminister,

I can confirm the partial fix works!

The installation was easy on our AndroidTV Box.
- Install latest Kodi RC
- Enable Inputstream.adaptive under add-on settings
- "libwidevinecdm" is a Chrome library. Since Android has Chrome brower built-in,
this lib was already installed.
- Installed your Pull request.
- Went to add-on settings and selected the HD stream
- Enabled subtitles

= Confrim: Works!

Might not close this ticket since the HLS stream is not yet supported by input stream.adaptive
Do you have an idea how much bandwith the HD stream uses vs the non-HD stream?

Many thanks!
You Rock!

**Comment by mediaminister** [comment]
Thanks for testing and confirming.

Bandwidth usage:

non-HD 540p ~ 2,45 Mbps
HD 720p ~ 3,2 Mbps

One hour VRT NU in non-HD 540p quality consumes ~ 1,1 gigabyte and one hour HD 720p quality consumes ~ 1,4 gigabyte.

**Comment by mediaminister** [comment]
Not really, for the "Team Scheire" case the VRT NU-team provided separate subtitle files but only for the foreign language programs that already have hardcoded subtitles for everyone.
These subtitle files are only relevant for people who can't read subtitles on a tv-screen and use a text-to-speech program to read the subtitles aloud.

The subtitles for hearing impaired people are contained in the HLS- and MPEG-DASH-streams. I know where to find the hyperlinks. Kodi 18 already supports the MPEG-DASH TTML-subtitling out of the box, but for the HLS-streams we still have to find a solution.

I might have a solution cause I recently found out that the WEBVTT-subtitles are not only available as fragmented parts but are also as a whole separate file.

**Comment by vasonline** [comment]
Hi mediaminister,

Yesterday and today I am unable to play the protected streams om our AndroidTV Box.
Does it still work for you?
I haven't changed anything
If I go to:
* Add on settings
* Disable the HD stream
Then the livestream works.

Excuse my little knowledge on this subject. 
Is there a way I can manage to get a log/error message?

Greetings and thanks!

**Comment by mediaminister** [comment]
DRM still works on Linux with Kodi 18 and libwidevinecdm.so.

I suspect Google is blacklisting some non-certified Widevine devices. You should test a couple of other DRM-protected services like Netflix or VTM. If none of these services work, that is very bad news for your AndroidTV box. 

Could you provide the kodi log? File location is documented here: https://kodi.wiki/view/Log_file/Advanced#Log_Files

> Note: The first folder might be different on various devices:

    /data/org.xbmc.kodi/cache/temp/kodi.log

    /sdcard/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log

    /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log

**Comment by mediaminister** [comment]
I made a new [pull request](https://github.com/pietje666/plugin.video.vrt.nu/pull/43) in which subtitling is available again for the on-demand streams on Kodi installations that don't have inputstream.adaptive or Widevine CDM installed.

So subtitling should always work with the on-demand streams when VRT provides it.

On the livestreams, subtitling only works with Widevine CDM for now. I have to investigate further how I can make it work with the HLS-livestreams.

**Comment by vasonline** [comment]
Hi,

Thanks!
I will look at the log location.
Here is a screenshot of the DRM Info.

![dscn5230 medium](https://user-images.githubusercontent.com/43968133/50157457-bdf6cf80-02d1-11e9-9509-0a658e89a860.JPG)

**Comment by mediaminister** [comment]
The DRM Info confirms security level L1, so DRM-protected should work. I'll wait for your Kodi-log to investigate the problem. If you could provide a Kodi Debug-log, that would be even better.
You can turn Debug logging on in the Kodi settings screen: https://kodi.wiki/view/Log_file/Advanced#GUI_settings

**Comment by dagwieers** [comment]
With the release of the plugin v1.5.0 I think this issue can be closed ?
