### ISSUE TITLE
Addon stopped working on content.find('h1').text

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#34]
**Describe the bug**
In between watching "De klas" and wanting to watch "Iedereen kiest" the addon stopped working. Nothing works at the moment, except livestreams.

It seems that the formatting has changed again, so we can't fall back on older expectations.

**(please complete the following information):**
 - LibreELEC 8.90.006
 - Kodi 18.0-BETA3

**Log (if available)**
```log
01:14:54.933 T:1427108720   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<-
-
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'find'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/addon.py", line 43, in <module>
                                                router(sys.argv[2][1:])
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/addon.py", line 32, in router
                                                vrt_player.show_videos(params['video'])
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py", 
line 124, in show_videos
                                                title_items.extend(self.__get_single_video(relevant_path.url, soup))
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py", 
line 178, in __get_single_video
                                                list_item_title = content.find('h1').text
                                            AttributeError: 'NoneType' object has no attribute 'find'
                                            -->End of Python script error report<--
```

**Comment by pietje666** [comment]
They change their site too often too my likings *yawn*

**Comment by dagwieers** [comment]
So why close this ? At least if you keep it open people can discuss/report solutions ?

**Comment by dagwieers** [comment]
Thanks, you're a star ! :-D

PS I think it would be nice if we could add some more information when we have specific exceptions (that relate to scraping/parsing issues). If we could dump the payload, or give some specific insight, it could be easier for anyone to understand what is going on. And we could also offer some additional information to the end-user, like a pop-up saying "This issue is caused by the VRT changing the web interface (the only interface to VRT.NU that currently exists). Please check http://github.com/pietje666/plugin.video.vrt.nu/issues for known issues and fixes."

**Comment by dagwieers** [comment]
Also, is there a possibility to get the fixes to the users faster ? Not sure what the process is.
