### ISSUE TITLE
Idea: Implement more resilience into the scraper/parser

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#35]
**Describe the bug**
It's unfortunate that there is no better API to VRT.NU (especially since we all pay for this service anyway and the VRT is ending DVB-T free-to-air soon).

But that doesn't mean we cannot improve the experience for end-users:

- If the parser fails, dump the payload and URL so people have an easier time understanding what we expect and what changed, and offer a fix.

- If the parser fails, on non-critical metadata (and I guess most is) we could replace it with a stub identifier, but still offer the video's. In this case the end-user may not see e.g. the titles, but can still select a video to play

- If the parser fails, provide a warning (in case we do continue) or an error (in case we cannot) with some more information:

  - *This issue is caused by the VRT changing the web interface (the only interface to VRT.NU that currently exists).*

  - *Please check http://github.com/pietje666/plugin.video.vrt.nu/issues for known issues and fixes.*

  - *Or investigate the logs to fix this yourself and contribute the fix.*

- Maybe we can have a better/faster distribution mechanism for this add-on. E.g. we can create our own repository that would automatically get the latest version. Which means if we release a new version, it could be a matter of minutes/hours to have Kodi update the add-on, rather than days.

**Comment by pietje666** [comment]
Guess ill just have to await your pull request   :D.

**Comment by pietje666** [comment]
I guess we can close this in favor of #57 . Right now a big part is already being scraped by calling the search api which will vastly improve resilience. For the future i am planning to change the A-Z scraping / category scraping as well using the api.
