### ISSUE TITLE
Werkend account met geverifieerd telefoonnummer werkt niet in add-on

### ISSUE THREAD

**Issue by dimsdupont** [pietje666/plugin.video.vrt.nu#366]
### Describe the bug ###
Een account met geverifieerd telefoonnummer werkt op vrt nu webpagina.

In Kodi krijg ik error"The program cannot be played. To view this program outside of Belgium, you first have to validate a Belgian mobile phone number on the VRT NU website" met dezelfde credentials.

### To Reproduce ###
To Reproduce
1. Go to Live TV 
2.  Click on  Eén live
3.  -
4. See error "The program cannot be played. To view this program outside of Belgium, you first have to validate a Belgian mobile phone number on the VRT NU website" met dezelfde credentials.

### Expected behavior ###
Look like tv on Kodi with same account used and working on https://www.vrt.be/vrtnu/livestream/

### Additional context ###
Operating system: Windows 7
Kodi version: 17.3
Addon version: 2.0.0
Using a VPN: no
Country you are using the addon from: Finland

![kodi_vrt_nu](https://user-images.githubusercontent.com/52605428/60758623-d0dcb180-a021-11e9-98df-bd69d143b033.JPG)

**Comment by dimsdupont** [comment]
Account met geverifieerd telefoon nummer werkt op vrt nu webpagina. 
In Kodi krijg ik error"The program cannot be played. To view this program outside of Belgium, you first have to validate a Belgian mobile phone number on the VRT NU website" met dezelfde credentials.

To Reproduce
1. Go to Live TV 
2.  Click on  Eén live
3.  -
4. See error "The program cannot be played. To view this program outside of Belgium, you first have to validate a Belgian mobile phone number on the VRT NU website" met dezelfde credentials.

Expected behavior.
Look like tv on Kodi with same account used and working on https://www.vrt.be/vrtnu/livestream/

Additional context
Operating system: Windows 7
Kodi version: 17.3
Addon version: 2.0.0
Using a VPN: no
Country you are using the addon from: Finland

![kodi_vrt_nu](https://user-images.githubusercontent.com/52605428/60758623-d0dcb180-a021-11e9-98df-bd69d143b033.JPG)

**Comment by mediaminister** [comment]
Temporary workaround: First play an on demand episode for a couple of seconds, than play livestream again. I'm working on a fix.

**Comment by dagwieers** [comment]
I guess we should release a v2.0.1 with a fix for this, but we could also add the newer functionality, so maybe v2.1.0 instead?

**Comment by mediaminister** [comment]
If the newer functionality doesn't break existing things, it's okay for me to make a 2.1.0 release.

**Comment by dagwieers** [comment]
I currently have this listed:

- Start a video by channel/start time (@mediaminister)
- Fix an issue with roaming VRT tokens (@mediaminister)
- Use notifications for various events related to tokens/cache/credentials (@dagwieers)
- Add YouTube channel support (@dagwieers)
- Add Radio 1 live stream (@dagwieers)
- Improve credential input (@michaelarnauts)

Not sure if you want to redo the *play video by start time* now, or if we want to do that later.

**Comment by dimsdupont** [comment]
tokens verwijderen en het herinstellen van  email address + paswoord geprobeerd zonder success ivm #366

**Comment by mediaminister** [comment]
Probeer volgende versie eens te installeren in Kodi via zip-bestand, deze bevat een fix voor het probleem:
[plugin.video.vrt.nu-2.0.0-3504229.zip](https://github.com/pietje666/plugin.video.vrt.nu/files/3366157/plugin.video.vrt.nu-2.0.0-3504229.zip)

**Comment by dagwieers** [comment]
@dimsdupont Kunnen we een bevestiging krijgen dat onze fix het probleem oplost? Ik zou graag een nieuwe release maken, maar ik weet dus niet of dat zinvol is.

Stel dat het probleem niet opgelost is in deze release, dan moeten we alsnog een nieuwe release doen. Liever niet.

**Comment by dimsdupont** [comment]
opgenomen programmas werken nu maar live tv doet niks, geen error

**Comment by mediaminister** [comment]
Het zou moeten werken.
Probeer eens het volgende:
- Credentials/Logingegevens instelling terug op Defaults/Standaard zetten
- Terug naar livestream menu en opnieuw inloggen
- Bij instellingen Troubleshouting InputStream Adaptive aan of uitzetten.

Als het probleem niet opgelost raakt, zou je dan een Kodi logfile kunnen uploaden hier?
Instructies op https://kodi.wiki/view/Log_file

**Comment by dimsdupont** [comment]
geen zin om een volledige log file te uploaden (te veel info) maar hopelijk helpt deze :

-------------------
15:39:03.978 T:6924   ERROR: ffmpeg[1B0C]: [tls] Creating security context failed (0x80090302)
15:39:03.978 T:6924   DEBUG: Error, could not open file https://live-vrt.cdn.eurovisioncdn.net/groupc/live/8edf3bdf-7db3-41c3-a318-72cb7f82de66/live_aes.isml/live_aes-audio_track_0_dut=128000-video=3000000.m3u8?hd

---------------

15:39:03.641 T:6924  NOTICE: Creating InputStream
15:39:03.642 T:6924   DEBUG: CurlFile::Open(107AF048) https://live-vrt.cdn.eurovisioncdn.net/groupc/live/8edf3bdf-7db3-41c3-a318-72cb7f82de66/live_aes.isml/live_aes-audio_track_0_dut=128000-video=3000000.m3u8?hd
15:39:03.658 T:1508    INFO: CPythonInvoker(13, C:\Users\****\AppData\Roaming\Kodi\addons\plugin.video.vrt.nu\addon.py): script successfully run
15:39:03.668 T:1508    INFO: Python script stopped
15:39:03.669 T:1508   DEBUG: Thread LanguageInvoker 1508 terminating
15:39:03.922 T:6924  NOTICE: Creating Demuxer
15:39:03.978 T:6924   ERROR: ffmpeg[1B0C]: [tls] Creating security context failed (0x80090302)
15:39:03.978 T:6924   DEBUG: Error, could not open file https://live-vrt.cdn.eurovisioncdn.net/groupc/live/8edf3bdf-7db3-41c3-a318-72cb7f82de66/live_aes.isml/live_aes-audio_track_0_dut=128000-video=3000000.m3u8?hd
15:39:03.978 T:6924   ERROR: CVideoPlayer::OpenDemuxStream - Error creating demuxer
15:39:03.978 T:6924  NOTICE: CVideoPlayer::OnExit()
15:39:03.978 T:6924   DEBUG: CApplication::OnPlayBackStopped: play state was 1, starting 1
15:39:03.978 T:6924   DEBUG: Thread VideoPlayer 6924 terminating
15:39:03.978 T:5552   DEBUG: CApplication::OnPlayBackStopped: play state was 3, starting 0
15:39:03.978 T:5552   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vrt.nu/play/id/vualto_een_geo]
15:39:03.978 T:5552   DEBUG: Playlist Player: no more playable items... aborting playback
15:39:03.979 T:6044   DEBUG: Thread BackgroundLoader start, auto delete: false
15:39:03.981 T:5552  NOTICE: CVideoPlayer::CloseFile()
15:39:03.981 T:5552  NOTICE: VideoPlayer: waiting for threads to exit
15:39:03.981 T:5552  NOTICE: VideoPlayer: finished waiting
15:39:03.981 T:5552   DEBUG: CRenderManager::DeleteRenderer - deleting renderer
15:39:03.981 T:5552  NOTICE: CVideoPlayer::CloseFile()
15:39:03.981 T:5552  NOTICE: VideoPlayer: waiting for threads to exit
15:39:03.981 T:5552  NOTICE: VideoPlayer: finished waiting

**Comment by mediaminister** [comment]
Ik kan het probleem jammer genoeg nog niet lokaliseren. 

Ik heb nogmaals getest op Windows 10 met Kodi 17.3 en een Deens IP-adres en alles werkt perfect.

Uit je log kan ik opmaken dat er een probleem is met ffmpeg en het openen van een https-verbinding, misschien is dat gerelateerd aan Windows 7. Indien mogelijk probeer je eens de livestream te openen op een andere Kodi-installatie.

Om uit te sluiten of de oorzaak van jouw probleem aan de VRT NU add-on ligt, heb ik een debug log nodig. Daarvoor moet je bij de add-on settings Troubleshouting -> Log Level -> Debug instellen.

**Comment by michaelarnauts** [comment]
@dimsdupont zeker dat inputstream.adaptive geïnstalleerd is? Ik kreeg een zeer gelijkaardig error wanneer dat niet geïnstalleerd was.

**Comment by mediaminister** [comment]
Er zat toch nog een bug in de vorige versie wanneer je telefoonnummer niet is gevalideerd.
Test volgende versie eens: 
[plugin.video.vrt.nu-2.1.0-07b5fc8.zip](https://github.com/pietje666/plugin.video.vrt.nu/files/3383493/plugin.video.vrt.nu-2.1.0-07b5fc8.zip)

**Comment by dagwieers** [comment]
@dimsdupont Kan je bevestigen dat het wel werkt met bovenstaande versie?

**Comment by dagwieers** [comment]
@dimsdupont Het zou leuk zijn als we dit konden afsluiten. Kan je bevestigen dat het werkt met deze fix ?

**Comment by mediaminister** [comment]
I looked into this again and found a small bug introduced in https://github.com/pietje666/plugin.video.vrt.nu/commit/09b9e86db3eaaa0c7662a9e8f0c88d480401fc61

I'm firmly convinced that an account with a validated Belgian mobile phone number works in the EU, I tested with a Danish VPN.
You can test this also with the following test release:
[plugin.video.vrt.nu-2.1.1-roaming-bae3e18.zip](https://github.com/pietje666/plugin.video.vrt.nu/files/3490378/plugin.video.vrt.nu-2.1.1-roaming-bae3e18.zip)

However it is still possible that you get this error message because of another undetected bug.
You always get this message if the add-on fails to get a roaming token after the stream api returned an "INCOMPLETE_ROAMING_CONFIG" message.

**Comment by dagwieers** [comment]
Kunnen we nog iets doen voor dit issue?
Of wachten we gewoon tot er iemand een nieuwe vector vindt waarin het gelijkaardig faalt? :-)

**Comment by mediaminister** [comment]
Ik beschouw dit probleem als opgelost. Ik kan het probleem niet meer reproduceren na de laatste fix: https://github.com/pietje666/plugin.video.vrt.nu/commit/51451e87b163ac1a68679f744d56ab9abbf1a49b

Voor mijn part mag dit issue gesloten worden.
