### ISSUE TITLE
Livestreams fail to start

### ISSUE THREAD

**Issue by pietje666** [pietje666/plugin.video.vrt.nu#37]
Please use this template, it really helps me to tackle bugs more easily when everything is filled in a structural manner

**Describe the bug**
Livestreams not working anymore. Apparently you need to be logged in now.

**To Reproduce**
1. Go to Livestreams
2. Click on Canvas
3. See error

**Expected behavior**
Livestream starts to play

**(please complete the following information):**
 - Operating system: Windows
 - Kodi Version: 17.6

**Additional context**
- Using a VPN: No
- Country you are using the addon from: Spain (Tenerife) but normally from Belgium

**Comment by skerit** [comment]
Are you unable to login? Because I just watched Canvas & één on my Libreelec installation.

**Comment by pietje666** [comment]
@skerit were you watching livestreams? Anyway changed code so it will login as well to get the token.

**Comment by debaze** [comment]
> I'm using the stream url directly in TVHeadend, and it is working fine without authentication. Also in vlc, so I'm not sure why a login us suddenly needed.

It seems that the token is needed to retrieve the stream URI rather than to play it. Note that for watching livestreams in the browser through VRTNU site, authentication is required.

It could be an option to avoid the need for registration (for livestreams) by hard-coding the stream URI in the application.

**Comment by michaelarnauts** [comment]
Oh, I assumed that the URLs were indeed hardcoded in the application.

**Comment by pietje666** [comment]
They were until they stopped working. I think they change the livestream urls quite often that's why i get them through the service.
