### ISSUE TITLE
Autostart VRT.nu plugin with autoexec.py

### ISSUE THREAD

**Issue by vasonline** [pietje666/plugin.video.vrt.nu#38]
**Describe the bug**
To make it easier for watching TV We want Kodi to start the Vrt.nu Plugin automatically.

**To Reproduce**
Create file "autoexec.py" in folder: \Kodi\userdata
https://kodi.wiki/view/Autoexec.py
Add the follwing text to "autoexec.py":

import xbmc
xbmc.executebuiltin("RunScript(plugin.video.vrt.nu)")

**Expected behavior**
Kodi lauches and VRT.nu plugin started
Instead: Kodi starts and gives 'VRT.nu Error"

Would you be so kind to have a look?
Thanks in advance!

Here is the output from Kodi.log
Happens on Windows and Android
(same message - just different paths)

12:00:28.621 T:3000 WARNING: RunScript called for a non-script addon 'plugin.video.vrt.nu'. This behaviour is deprecated.
12:00:33.313 T:3324   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "C:\Users\Beheerder\AppData\Roaming\Kodi\addons\plugin.video.vrt.nu\addon.py", line 12, in <module>
                                                _handle = int(sys.argv[1])
                                            IndexError: list index out of range
                                            -->End of Python script error report<--

**Comment by pietje666** [comment]
12:00:28.621 T:3000 WARNING: RunScript called for a non-script addon 'plugin.video.vrt.nu'. This behaviour is deprecated. 

I think you should use RunAddon instead of runscript

**Comment by pietje666** [comment]
No problem :)

**Comment by dagwieers** [comment]
Hmmm, Kodi has an interface to select what to show on startup. In **Settings » Interface » Startup » Startup Settings** you have two options **Perform on startup** and **Startup window**. I wonder if there's a possibility that an addon can hook into this and add an option.

Would be nice if this was possible without the need to resort to editing files on disk.

**Comment by dagwieers** [comment]
Also, should we maybe open the Wiki and start adding information like this for others ? If we close this issue, it will not be easily found.

**Comment by dagwieers** [comment]
This is now documented here: https://github.com/pietje666/plugin.video.vrt.nu/wiki/Autostart

**Comment by dagwieers** [comment]
I just added documentation to the Wiki page on how to go automatically into a menu, e.g. the Live TV listing. Feedback or improvements appreciated.
