### ISSUE TITLE
Add TV Guide in the channels menu

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#391]
### Describe the feature ###
It would be nice if also the TV Guide would be available in the channels menu so that it becomes a single interface to *all* content (Live channel, VOD content, YouTube channel *and* TV guide).

Unfortunately the TV Guide was designed to first specify the date, and then the channel (which makes a lot of sense for a TV Guide). But for the channels menu, I would like to go to the date-selection for a given channel (so a different order). This would require another API interface, maybe `/tvguide/channel/<channel>/<date>` and change the existing interface to `/tvguide/date/<date>/<channel>` ?

What do others think?

**Comment by michaelarnauts** [comment]
I've always find it strange that I first have to select a date, and then a channel, so if it can be reversed, I'm all in favor :)

**Comment by dagwieers** [comment]
The reason for this is simple, if you want to see what is on today, you select today, and then go over the channels. Just like in a magazine, you first go to the right day and then you have an overview of what's on on the various channels.

So I don't plan to reverse it for the TV Guide, I only need the other interface for the by-channel views.
