### ISSUE TITLE
version 2.1.0 fails to install

### ISSUE THREAD

**Issue by sqlksjdfieu987** [pietje666/plugin.video.vrt.nu#392]
### Describe the bug ###
Addon version 2.1.0 fails to install. 

Reading the logs I noticed it's about the module 'script.module.routing'. The link seems to be broken.

18:04:30.347 T:140316757706496   ERROR: CCurlFile::Open failed with code 404 for https://raw.githubusercontent.com/djwayne1985/repository.T2K/master/zips/script.module.routing/script.module.routing-0.2.1.zip
18:04:30.348 T:140316757706496   ERROR: CAddonInstallJob[script.module.routing]: failed to download special://home/addons/packages/script.module.routing-0.2.1.zip
18:04:30.350 T:140316757706496   ERROR: CAddonInstallJob[plugin.video.vrt.nu]: failed to install dependency script.module.routing

### Additional context ###

- Operating system: Debian GNU/Linux 9.9 (stretch)
- Kodi version: 17.1+dfsg1-3 (Debian 'oldstable')
- Addon version: 
- Using a VPN: no
- Country you are using the addon from: Belgium

**Comment by dagwieers** [comment]
Is it possible you have other repositories enabled that also offer the **script.module.routing** module?
The version from the official Kodi repositories should be coming from a mirror like: http://ftp.snt.utwente.nl/pub/software/xbmc/addons/krypton/plugin.video.vrt.nu/plugin.video.vrt.nu-2.1.0.zip

Your log seems to indicate it is not coming from an official Kodi mirror.
Can you provide me with a list of repositories you have included so I can investigate which one is bogus?

**Comment by dagwieers** [comment]
I bet this repository is called: T2K. https://github.com/djwayne1985/repository.T2K/
Which seems to be broken. If you disable or remove that repository, things should work out fine.
You may have to refresh the official Kodi repository (or wait until that happens, every 24 hours).

**Comment by sqlksjdfieu987** [comment]
Hi,

I disabled the repo and indeed, that did the trick.

I am just using the default debian repository, never added a repo manually after installing the OS.

**Comment by dagwieers** [comment]
I would be surprised, this is not a normal repository. You may have installed an add-on from a 3rd party that added its own repository.

In any case, thanks for reporting back!
