### ISSUE TITLE
Better artwork for the plugin

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#393]
### Describe the feature ###
So I have had some feedback from various people about the current icon/fanart of the plugin.
It doesn't bother me, but it seems to bother some people because it is "not very inviting".

Someone suggested to use the artwork of the Radio plugin (especially since it includes TV channels as well) . So one option is we take that fanart, but use another main color, e.g. green or purple ?

Or we find something else altogether.

**Comment by mediaminister** [comment]
I made something new based on the current art and the radio plugin artwork.
![test](https://user-images.githubusercontent.com/45148099/62624750-0d067900-b924-11e9-8bd8-0d432aaaf1fa.png)
Please let me know if this need changes (colors, composition, etc...).

**Comment by dagwieers** [comment]
Well done!

cc @pietje666

**Comment by mediaminister** [comment]
@dagwieers @pietje666 If no changes are needed, I have the new artwork ready at https://github.com/mediaminister/plugin.video.vrt.nu/tree/artwork and I will create a pull request next week.

**Comment by michaelarnauts** [comment]
If you can create a similar skyline of Vilvoorde, that could be useful somewhere :p

**Comment by dagwieers** [comment]
@mediaminister My preference would be to use the new fanart by default (as background) for all views that have no fanart instead of showing a fuzzy icon. What do you think ?

**Comment by mediaminister** [comment]
High resolution is always better than fuzzy. Especially in a big TV screen environment.

**Comment by pietje666** [comment]
looks good! :)

**Comment by mediaminister** [comment]
Okay, I created a pull request: https://github.com/pietje666/plugin.video.vrt.nu/pull/416

**Comment by dagwieers** [comment]
Closed by #416
