### ISSUE TITLE
Watch anonymously using `youtube-dl`

### ISSUE THREAD

**Issue by stroobandt** [pietje666/plugin.video.vrt.nu#40]
On any GNU/Linux platform it is possible to watch the live VRT Akamai streams (almost) anonymously.
That is, one's IP-address might still be recorded.

Nonetheless, watching without logging in is done by opening the live Akamai `.m3u8` stream using the Python `youtube-dl -o - "akamai_stream_url"` command and piping its output to a media player like `| vlc -`

Would it be possible to implement this solution in your Kodi plugin?
It might be that this also solves your overheating problems.

> In my opinion, it is none of the VRT's business to know my e-mail address, whether I am watching or what I am watching. Watching with DVB-T or analogue cable happened anonymously. This is no longer the case with VRT NU or the overly expensive Telenet.

**Comment by stroobandt** [comment]
@mediaminister That is too cool! Thank you for that. I will try it out in the coming days.

**Comment by stroobandt** [comment]
For those who want to test this at the command line of a GNU/Linux box, here are the commands:

    #Één
    youtube-dl -o - "https://live-vrt.akamaized.net/groupc/live/8edf3bdf-7db3-41c3-a318-72cb7f82de66/live_aes.isml/playlist.m3u8" | vlc -

    #Canvas
    youtube-dl -o - "https://live-vrt.akamaized.net/groupc/live/14a2c0f6-3043-4850-88a5-7fb062fe7f05/live_aes.isml/playlist.m3u8" | vlc -

    #Ketnet
    youtube-dl -o - "https://live-vrt.akamaized.net/groupc/live/f132f1b8-d04d-404e-90e0-6da1abb4f4fc/live_aes.isml/playlist.m3u8" | vlc -

**Comment by stroobandt** [comment]
When is the «live stream without logging in» feature going to be available in a new release, please?

**Comment by stroobandt** [comment]
Thanks! I will test it out in the coming days.

**Comment by pietje666** [comment]
I think this is fixed and can be closed right now?

**Comment by mediaminister** [comment]
For me, this can be closed. You can watch the livestreams without logging in with a VRT-account.
