### ISSUE TITLE
Implement pause and rewind for live streams

### ISSUE THREAD

**Issue by glenndemunck** [pietje666/plugin.video.vrt.nu#400]
### Describe the feature ###

At the moment it's not possible to pause and rewind live streams. However, it's possible in any other stream. 

It would be nice to implement the same feature for live streams.

**Comment by dagwieers** [comment]
If I start a live stream (e.g. Eén) I can immediately rewind 15 minutes back, and pause works as well.
This is on LibreELEC v9.0.2 and Kodi v18.2 using inputstream.adaptive and Widevine.

**Comment by glenndemunck** [comment]
It's working now, Widevine was not enabled. 
Did not knew that enabling Widevine adds extra functionality to the live streams. 

Thank you!

**Comment by dagwieers** [comment]
I did not either. This may be something to look into and/or document.

Thanks for reporting back.

**Comment by dagwieers** [comment]
Relates to #854
