### ISSUE TITLE
Use of kodi widgets for the addon gives errors

### ISSUE THREAD

**Issue by skank01** [pietje666/plugin.video.vrt.nu#403]
Wanneer ik kodi widgets wil toevoegen naar delen van de addon (maakt niet uit welk onderdeel), dan krijg ik bij alles errors.
Gebruikte kodi skin: embruary
Laatste kodi build (leia)

**Comment by michaelarnauts** [comment]
Welke error krijg je? Kan je een stukje van je kodi.log posten?

**Comment by skank01** [comment]
https://paste.kodi.tv/ixejapurit

dont mind the emby and netflix errors

**Comment by mediaminister** [comment]
Ik heb de log bekeken en de oorzaak van het probleem gevonden.
De widget functionaliteit in de [Embruary skin](https://github.com/sualfred/skin.embuary) ondersteunt uitsluitend `plugin://` urls **met** trailing slash terwijl de VRT NU add-on uitsluitend `plugin://` urls **zonder** trailing slash ondersteunt.
De VRT NU add-on ondersteunt bijvoorbeeld uitsluitend `plugin://plugin.video.vrt.nu/livetv` terwijl de widgets in de Embruary skin uitsluitend doorverwijzen naar `plugin://plugin.video.vrt.nu/livetv/` met een `No route to path` routing error als  gevolg.

Twee mogelijke oplossingen:
- De VRT NU add-on voegt support toe voor `plugin://` urls **met** trailing slashes.
- De Embruary skin voegt support toe voor `plugin://` urls **zonder** trailing slashes.

Het probleem bij de Embruary skin situeert zich hier:
https://github.com/sualfred/skin.embuary/blob/6def245a8ac679585ddbb31c96ced20586f987c1/xml/Embuary_Variables.xml#L1524

Deze functionaliteit werd toegevoegd in volgende commit: https://github.com/sualfred/skin.embuary/commit/716150172e989ec2f948f1f31d3ebf4386ee287d

**Comment by skank01** [comment]
Top om uit te zoeken ! waarvoor dank.

Dus ofwel voegen jullie support toe? ofwel sualfred in de embruary skin?

Euh, naar wie kijk ik nu ? :p

**Comment by michaelarnauts** [comment]
Ik vind het niet onlogisch dat URL's naar een directory listing met een training slash eindigen. URL's naar een live stream of een programma uit VOD lijkt me dan geen trailing Slash te hebben.

Het lijkt me dan ook dat dit common practice is, of die skin zou vol met zo'n issues staan?

**Comment by skank01** [comment]
Ik heb anders geen issues ermee...
Althans bv met youtube addon enzo, werkt alles perfect

**Comment by dagwieers** [comment]
Wat zijn Kodi widgets ? Ik heb er nog nooit van gehoord.

**Comment by michaelarnauts** [comment]
Hiermee kan je directory listings rechtstreeks in een bepaalde view krijgen. De standaard skin ondersteund het niet, maar andere wel. Zo zou je bijvoorbeeld een top level menu kunnen maken met daarin de live channels van VRT nu, met eronder de channels van een andere plugin.

Vermoedelijk zijn er nog wel andere use cases, maar ik gebruik enkel de default skin, dus verder weet ik er ook niet van.

**Comment by mediaminister** [comment]
> Ik vind het niet onlogisch dat URL's naar een directory listing met een training slash eindigen. URL's naar een live stream of een programma uit VOD lijkt me dan geen trailing Slash te hebben.

Het gebruik van trailing slashes is niet onlogisch voor mappen, maar dat moet steeds de autonome keuze van de add-on aanbieder kunnen zijn. Daarenboven gebruikt Kodi voor het `special://` protocol ook url's zonder trailing slash: https://kodi.wiki/view/Special_protocol

> Het lijkt me dan ook dat dit common practice is, of die skin zou vol met zo'n issues staan?

Geen idee wat Kodi betreft. Vermoedelijk zijn er wel add-ons te vinden die geen trailing slash ondersteunen.
Op het web is het niet ongewoon: https://www.google.com/search versus https://www.google.com/search/

Ik ben dus van mening dat de bug zich situeert in de de Embruary skin, een trailing slash mag geen verplichting zijn, het moet steeds optioneel zijn. Ik heb de bug gefixed in de Embruary skin en hieronder vind je een zip-bestand met de bugfix.

@skank01 Kan je volgend zip-bestand met een aangepaste versie van de Embruary skin eens installeren in Kodi. Laat weten of de widgets functioneren voor de verschillende add-ons, inclusief VRT NU.
https://github.com/mediaminister/skin.embuary/raw/zip/skin.embuary-leia-18.7.14.trailingslash.zip

**Comment by mediaminister** [comment]
Ik heb upstream een pull request gemaakt: https://github.com/sualfred/skin.embuary/pull/31
Ondertussen al gemerged na enkele aanpassingen. Het kan soms snel gaan.

Hou https://github.com/xbmc/repo-skins/pulls in de gaten, in de volgende officiële release van de Embruary skin zullen widgets met de VRT NU add-on gewoon werken.

Alle laatste wijzigingen zijn toegevoegd aan volgend zip-bestand zodat je nu al kan testen: https://github.com/mediaminister/skin.embuary/blob/zip/skin.embuary-leia-18.7.14.trailingslash.zip

**Comment by skank01** [comment]
Bedankt gasten! Top van jullie! Ik test dit asap. 
Enig idee wanneer de VTM.go add-on klaar zal zijn voor gebruik? Momenteel enkel een VTM.go en Stievie app maar die werkt niet lekker binnen kodi, gezien de tv geen touchscreen is.

Zullen deze 2 addons altijd blijven werken?

**Comment by mediaminister** [comment]
@skank01 Geen idee wat de toekomst brengt. Ik weet alleen dat er eerst nog een aantal bugs moeten gefixed worden vooraleer een VTM Go add-on überhaupt werkbaar zal zijn.

**Comment by skank01** [comment]
Dat zijn dan bugs ivm inputstream.Adaptive?
Das wachten op kodi zelf? Weten ze dit reeds?
Anyway, om dan alsnog aan de vtm kanalen te geraken is de enige optie restrospect addon?

Vraagje ivm deze addon nog, skin is ondertussen geupdate, ik probeer dit asap

Wat ik ook gemerkt heb zijn de logo's/covers/
Die zijn momenteel zwart/wit 
Dit oogt in widget niet zo mooi.

Is er een mogelijkheid/optie om die in kleur te hebben?
Iets als dit https://nl.wikipedia.org/wiki/Lijst_van_televisiekanalen_in_Belgi%C3%AB

**Comment by dagwieers** [comment]
@skank01 We hebben toegang tot zwart-wit en kleureniconen. Het liefst van al zou ik zwart-wit bullets hebben in de listing en gekleurde icons. Maar dat kan niet in Kodi (het is me alleszins nooit gelukt). Daarom gebruiken we momenteel zwart-wit iconen.

We kunnen een optie maken in de instellingen om dit te veranderen naar kleuren, of we kunnen beslissen om standaard kleuren te gebruiken. Ik sta open voor een debat hierover.

Ivm. Retrospect VTM support en VTM GO, het aanbod is verschillend en complementair op sommige gebieden. (Idem voor Eén.be web-scraping en VRT NU) Idem voor Stievie vs. VTM GO. Het aanbod van VTM GO is in alle opzichten beter en betrouwbaarder.

**Comment by skank01** [comment]
Is mij gelijk hoor, of het nu altijd is met kleuren (goed voor mij) of de mogelijkheid mits een optie aan of uitvinken..
Zou super zijn want nu oogt het wat oudbollig.

Ivm retrospect, ok maar vtm.go werkt nu nog niet.. dus heb ik alternatief ;) tot het wel werkt :p

**Comment by skank01** [comment]
Hey,

Het werkt!
Mag ik nog ff iets vragen..
Ik zie de bomen door het bos niet meer.

Zopas retrospect geinstalleerd, daar kan ik nu hetzelfde doen als vrt.nu addon + stievie dat me vtm enz geeft (gratis account)

Maar, ik heb geen tvgids...
Wat wel handig is..
Dan kom ik op volgende addon https://forum.kodi.tv/showthread.php?tid=120377
Echter moet ik url of xml ingeven, wat ik niet heb
Google geeft me dan volgend resultaat https://catch-up-tv-and-more.github.io/live_tv_installation/
Nog een andere app, catchup tv,

Wat is het verschil allemaal tussen jullie addons, retrospect, catchup tv.. enz
en dan die tvguide..

Hoe krijg ik dit nu allemaal ok?
en graag ook een tvgids voor belgische zenders...
Zou top zijn mocht ik jullie support krijgen

**Comment by dagwieers** [comment]
Ik heb een overzicht gemaakt op de volgende Wiki pagina:
https://github.com/pietje666/plugin.video.vrt.nu/wiki/Flemish-TV

Maar de TVGuide en Catchup TV addon staan er niet bij omdat ik niet vind dat ze bijdrage tot een groter gebruiksgemak.

**Comment by mediaminister** [comment]
> Het werkt!

Oké, dan kan dit issue gesloten worden.

> Wat is het verschil allemaal tussen jullie addons, retrospect, catchup tv.. enz
> en dan die tvguide..

Op de websites van die add-ons staat altijd wel een korte omschrijving.
Voor de VRT NU add-on is dit de volgende:
_plugin.video.vrt.nu is een Kodi-add-on voor het bekijken van alle live videostreams en alle video-on-demand-content die beschikbaar is op VRT NU._

> Hoe krijg ik dit nu allemaal ok?

Zoeken, lezen en uitproberen.

**Comment by dagwieers** [comment]
> We kunnen een optie maken in de instellingen om dit te veranderen naar kleuren, of we kunnen beslissen om standaard kleuren te gebruiken voor icons. Ik sta open voor een debat hierover.

Ik heb dit opnieuw geëvalueerd, maar we kunnen geen ander icon tonen als we een thumbnail in kleur tonen, als gevolg zijn de icons in kleur en dat ziet er niet goed uit in kleuren. Enkel wit ziet er proper uit.

**Comment by skank01** [comment]
> Ik heb een overzicht gemaakt op de volgende Wiki pagina:
> https://github.com/pietje666/plugin.video.vrt.nu/wiki/Flemish-TV
> 
> Maar de TVGuide en Catchup TV addon staan er niet bij omdat ik niet vind dat ze bijdragen tot een groter gebruiksgemak.

Hey Thx
Klopt, alleen mis ik dan nog een tvgids :p

**Comment by skank01** [comment]
> > We kunnen een optie maken in de instellingen om dit te veranderen naar kleuren, of we kunnen beslissen om standaard kleuren te gebruiken voor icons. Ik sta open voor een debat hierover.
> 
> Ik heb dit opnieuw geëvalueerd, maar we kunnen geen ander icon tonen als we een thumbnail in kleur tonen, als gevolg zijn de icons in kleur en dat ziet er niet goed uit in kleuren. Enkel wit ziet er proper uit.

Dus geen kleuren? Das erg jammer
Retrospect toont wel kleuren

**Comment by dagwieers** [comment]
> Ik denk wel dat Stievie free en payed, beide 720p uitsturen

Stievie is enkel 540p, ook met Stievie PREMIUM.

> Dus geen kleuren? Das erg jammer
> Retrospect toont wel kleuren

Retrospect toont geen icons.

**Comment by skank01** [comment]
> > Ik denk wel dat Stievie free en payed, beide 720p uitsturen
> 
> Stievie is enkel 540p, ook met Stievie PREMIUM.
> 
> > Dus geen kleuren? Das erg jammer
> > Retrospect toont wel kleuren
> 
> Retrospect toont geen icons.

Mmm vreemd dat kodi zegt dan dat het 720p is van stievie (via retrospect)
De vtm.go zou dan toch noodzakelijk worden :p hopelijk soon

Retrospect toont wel icons, zie bijlage mn widget.
Die in het wit is van de vrt nu addon de kleur is retrospect 
![TV](https://user-images.githubusercontent.com/53368406/62770731-ea976b80-ba9b-11e9-824f-a51d78e456e1.jpg)

**Comment by dagwieers** [comment]
> Retrospect toont wel icons, zie bijlage mn widget.
> Die in het wit is van de vrt nu addon de kleur is retrospect

Wat jij toont zijn de thumbnails, de icons waarover ik het heb zijn de bullets in een listing view.

**Comment by skank01** [comment]
Ok en ik kun je dan niet alleen thumbnails doen?
