### ISSUE TITLE
When credentials change, favorites are not updated

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#404]
### Describe the bug ###
I just noticed that when you change your credentials, your favorites (and recent favorites + offline favorites) are not being refreshed, so you see the favorites from the previous credentials. Easy to fix.

**Comment by mediaminister** [comment]
I'm working on a [fix](https://github.com/mediaminister/plugin.video.vrt.nu/tree/credentials) for this and meanwhile I found out https://github.com/pietje666/plugin.video.vrt.nu/commit/3c736c530056d2fa9397c4a310f0a8ba761443dc does not work and will never work because settings are changed after confirming the changes with the OK button.

Can anyone confirm my findings?

**Comment by dagwieers** [comment]
I was planning to fix this issue as well, thanks for taking it.

I can confirm that it doesn't work within the settings, you have to first press OK to save it, and then go back. Maybe we ought to detect when credentials have changed, and do a test only then (with a notification or a pop-up).

**Comment by michaelarnauts** [comment]
Strange. It should work since the option="close" saves the settings before closing the dialog. This is how I've seen it work.

**Comment by dagwieers** [comment]
@michaelarnauts We don't close the dialog anymore, we show a notification.I guess that broke it.

**Comment by michaelarnauts** [comment]
Ah. I missed that change. You need to close it. That's why the original code reopened the settings again after the check.

**Comment by mediaminister** [comment]
I removed `check_credentials` completely on my test branch and implemented the same behaviour via the OK-button: https://github.com/mediaminister/plugin.video.vrt.nu/tree/credentials

**Comment by dagwieers** [comment]
@mediaminister That's looking good. A nice cleanup as well. Perfect for the upcoming v2.2.0 ;-)

**Comment by mediaminister** [comment]
Fixed in https://github.com/pietje666/plugin.video.vrt.nu/pull/410
