### ISSUE TITLE
Thought about creating a Play Sports addon?

### ISSUE THREAD

**Issue by piejanssens** [pietje666/plugin.video.vrt.nu#418]
Widevine DRM is supported by the Kodi adaptive inputstream module. In theory a PlaySports addon can work. Ever thought of creating such an addon?

**Comment by michaelarnauts** [comment]
This is unrelated to the VRT NU offering. You should try contacting the author of the Yelo TV Kodi Plugin. More information here: https://kodi.wiki/view/Add-on:Yelo
