### ISSUE TITLE
check that an episode has been watched not there on kodi 18.0

### ISSUE THREAD

**Issue by peno64** [pietje666/plugin.video.vrt.nu#42]
I know that kodi 18 is just in alfa so it could be that you want to ignore this for now, but as you can see in attached printscreen, when I use retrospect in kodi 18 (latest version) on raspberry PI 2, a small icon is shown before each episode. With kodi 17 this is not the case. However probably because of this, the checkbox that an episode has been watched is not there anymore and that is quite enoying. Is it by purpose that this small icon is shown in the episode list and
![screenshot049](https://user-images.githubusercontent.com/32430988/49688946-fb14d200-fb19-11e8-8b06-68ea26995cca.png)
 could it be that this makes the 'has been seen' check is not there anymore? If so, would you also not prefer to have the check instead of the icon? An example is vrt.nu, professor T

**Comment by pietje666** [comment]
Will look into this!

**Comment by peno64** [comment]
In fact Kodi 18 is already in release candidate mode so I think its release is not that far away anymore.
So very good that you will look into this.
Note that I use Kodo on Raspbery Pi

**Comment by pietje666** [comment]
So far i have no idea why it does not work, i would expect any changes that i should perform on my side to be listed here https://forum.kodi.tv/showthread.php?tid=303073 . I can find that there were some issues with the mark as watched features as well in for instance youtube addon etc so i hope its a kodi issue that will be solved

**Comment by peno64** [comment]
Other add-ons don't have this issue. For example your 'competitor' retrospect is not having this problem...

**Comment by pietje666** [comment]
Took my a while of trial and error before finding the culprit :(

**Comment by dagwieers** [comment]
When can we expect a new release? I would like to test the new candy ;-)

**Comment by pietje666** [comment]
Probably somewhere this week! I was pretty busy past weeks.

**Comment by dagwieers** [comment]
> Took my a while of trial and error before finding the culprit :(

Works great ! It registered what was watched when this was broken, so no harm done.

**Comment by peno64** [comment]
Where do you find this new version? I still only find 1.4.3

**Comment by peno64** [comment]
I created my own plugin.video.vrt.nu-1.5.0.zip file out of the github repo and as such I could install the 1.5 version and indeed it works fine now.
But still I wonder where dagwieers found this new version.

**Comment by pietje666** [comment]
here https://github.com/pietje666/plugin.video.vrt.nu/releases , and soon in kodi repo

**Comment by peno64** [comment]
great!
Do you have an example of the 720p Livestreams that need kodi 18 & widevine? I have both installed so I would like to test if this works ok.

**Comment by dagwieers** [comment]
@peno64 It should select 720p automatically. You can verify in Kodi by looking at the stream info (player process info) by pressing key "**o**" or possibly the **⋮☰** key on your remote. Worked out-of-the-box for me.
