### ISSUE TITLE
Add support for "Up Next" Addon

### ISSUE THREAD

**Issue by michaelarnauts** [pietje666/plugin.video.vrt.nu#420]
The "Up Next" Kodi addon provides netflix-like binge watching features. When an episode is finished, it can show a message to play the next episode. This works since an addon can emit a message with the information about the next episode.

More information is available here: https://forum.kodi.tv/showthread.php?tid=336747

Information on how to integrate is here: https://github.com/im85288/service.upnext/wiki/Addon-Integration

**Comment by dagwieers** [comment]
It looks interesting, but would need to understand how the interface works/behaves in detail, also:
- Only add official support when it is part of the official add-ons.
- Add it as an optional requirement
- Have a flag to disable it for our add-on (but enable it by default when installed)

**Comment by mediaminister** [comment]
Please take a look at my draft pull request: https://github.com/pietje666/plugin.video.vrt.nu/pull/521
