### ISSUE TITLE
Clearing tokens disable My Programs (favorites)

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#429]
### Describe the bug ###
So I discovered that a user would lose his My Programs menu when he clears his tokens. And there's no way to get your My Programs back, unless you first invalidate you login (use a wrong login) and then change it back again in order to force a new login token.

### To Reproduce ###
1. Go to Settings » Troubleshooting
2. Click on Clear VRT tokens
3. Go back to main menu
4. See My programs is missing, and nothing will bring it back

### Expected behavior ###
My programs remains listed even when tokens have been cleared.

### Additional context ###
- Operating system: LibreELEC v9.0.2
- Kodi version: 18.3
- Addon version: 2.2.0
- Using a VPN: no
- Country you are using the addon from: BE

**Comment by mediaminister** [comment]
You can easily get your "My Programs" back by starting an on demand stream.
I'll see how to fix this.
