### ISSUE TITLE
Prepare for the new TV season

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#450]
### Describe the feature ###
Starting from 1 september the new TV season is starting. We know there will be a new logo for Eén, and I expect important announcements wrt. VRT NU as well. The recent changes to the website that needed webscraper updates may also indicate something is coming.

I noticed VRT NU now shows "Favorieten" in the app (It used to be "Volgen", but there wasn't a separate listing in the app IIRC). We call this "Mijn programma's" to not confuse it with Kodi Favorites, but maybe we may want to realign the terminology?

Let's use this issue to discuss any needed changes that could go into an upcoming v2.2.2 release.

**Comment by dagwieers** [comment]
This is what we can expect for new content:
- https://www.vrt.be/vrtnws/nl/2019/08/12/dit-brengt-een-dit-najaar/

**Comment by mediaminister** [comment]
I'm all in favor to follow the terminology VRT NU is using.
I created a pull request with the new Een logo in the resource.images.studios repo.

**Comment by dagwieers** [comment]
Now let's hope they don't release that too soon :-D

**Comment by dagwieers** [comment]
I also would like to change the pictogram used for "Mijn programma's", rather than a headshot I would go for the :star: symbol as they do in the app.

**Comment by dagwieers** [comment]
I have opened #457 to prepare for the upcoming v2.2.2 release.

**Comment by dagwieers** [comment]
There was an update of the VRT NU app with the new Eén branding. I noticed that on Kodi it requires a reboot to get the new Eén studio icon?

**Comment by mediaminister** [comment]
Oh nice, the studio icons got released.
We could have avoided a reboot by clearing the texture cache for this icon like we do for the screenshots. But it's maybe a bit overdone to implement this just for a rebranding that happens only once every few years.

**Comment by dagwieers** [comment]
Indeed.
