### ISSUE TITLE
Opent niet meer

### ISSUE THREAD

**Issue by straphke** [pietje666/plugin.video.vrt.nu#46]
Sinds de update opent de vrtnu-addon niet meer. Kodi 18 geïnstalleerd, zelfde probleem. Terug naar 17.6, nog steeds. Draait op Rbpi3, LibreElec. 
Bij openen kom ik op pagina Series/VRT Nu: Bekeken
Geen inhoud op te zien...

**Comment by mediaminister** [comment]
Met zo weinig informatie, kan ik je niet meteen verderhelpen. Probeer het volgende eens:
- VRT NU-addon verwijderen
- VRT NU-addon herinstalleren
- Noodoplossing: het bestand Addons27.db in de map kodi/userdata/Database verwijderen, je verliest dan wel je gebruiksdata van alle addons.

Indien je geen oplossing vindt:
Kan je jouw Kodi-logbestand hier eens uploaden? Dan kunnen we de oorzaak beter achterhalen. Waar je het logbestand precies kan vinden, staat hier beschreven: https://kodi.wiki/view/Log_file/Advanced#Log_files

**Comment by straphke** [comment]
Verwijderen en herinstallatie werkt ook niet. In de log viewer krijg ik deze errors: T:1936920592 ERROR: Control 55 in window 10025 has been asked to focus, but it can't
T:1063195504 ERROR: GetDirectory - Error getting /storage/.kodi/cdm

**Comment by mediaminister** [comment]
Oké, de map met de Google Widevine CDM bestaat niet en daar loopt de addon op vast.

Ik heb een voorlopige fix, probeer eens volgend zip-bestand te installeren via de functie "Install from zip file": 
[plugin.video.vrt.nu.zip](https://github.com/pietje666/plugin.video.vrt.nu/files/2714837/plugin.video.vrt.nu.zip)

Laat me weten of de VRT NU-addon daarna werkt.

**Comment by straphke** [comment]
Ik probeer meteen.
Hier zou een debug log moeten zitten na herstart en opstart VRT Nu-addon: http://paste.kodi.tv/oriyegohev

**Comment by straphke** [comment]
Met het nieuwe zip-bestand blijft het probleem hetzelfde.

**Comment by mediaminister** [comment]
Oké, er zat dus een fout in mijn code, tweede poging: 
[plugin.video.vrt.nu.zip](https://github.com/pietje666/plugin.video.vrt.nu/files/2715023/plugin.video.vrt.nu.zip)

**Comment by straphke** [comment]
Dank alvast voor alle moeite!
Na nieuwe zip bleef de VRT Nu-addon maar laden bij openen. Na herstart alweer hetzelfde probleem en zelfde scherm als voordien.
Hier de log: http://paste.kodi.tv/nekonaponu

**Comment by mediaminister** [comment]
Ik zie geen errors meer van de VRT NU-addon en de log geeft aan dat de VRT NU-addon volledig ingeladen wordt. Ik denk dat je nu best zelf eens bekijkt of er iets mis is met jouw Kodi-installatie.

Misschien is er iets mis met de Kodi Database.  Een backup nemen van de map /storage/.kodi/userdata/Database en daarna Kodi starten met een lege database kan mogelijks een oplossing zijn. Indien gewenst kan je de backup van de Database daarna ook terugzetten.

Een verse installatie op een andere SD-kaart kan mogelijks ook aantonen dat het probleem niet bij de VRT NU-addon ligt.

Oudere versies van de addon kan je hier downloaden: https://github.com/pietje666/plugin.video.vrt.nu/releases

**Comment by mediaminister** [comment]
Oké, als het probleem voor jou opgelost is, dan mag je dit issue sluiten.
