### ISSUE TITLE
All season listing does not properly show season

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#503]
### Describe the bug ###
Due to a bug in Kodi the *"* All seasons"* listing shows all episodes numbered by episode only. This means the numbering goes up and restarts from 1 when browsing through episodes.

For local media Kodi shows SxE (4x01) in "* All seasons" episode listings, but it doesn't do that for add-ons.

**Comment by dagwieers** [comment]
This was reported and subsequently fixed in Kodi (see xbmc/xbmc#16371).
A fix already ships with Kodi 18.4 and Kodi 19.

**Comment by mediaminister** [comment]
I can confirm this is fixed in Kodi 18.4

**Comment by dagwieers** [comment]
Ok, let's close this. I don't want to wait for an official LibreELEC release for this.
