### ISSUE TITLE
Adding PG and PP related information

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#505]
### Describe the feature ###
I noticed that the VRT NU website now also shows PG and PP information, so with some luck this information is available somewhere.

This makes it possible to select what kind of content is desirable for the add-on, i.e. so that the children's profile does not see content for e.g. 12+ or 16+. Or PP (product placement) if you like.

**Comment by dagwieers** [comment]
I couldn't find where this information is coming from.

**Comment by mediaminister** [comment]
I only found this info in the html file, I doubt there is a public API:

```html
        <li class="guidelines">
            
            <span data-icon-single="product-placement">
                Product Placement
            </span>
            
      
        </li>
```
```html
        <li class="guidelines">
            
            
            <span data-icon-single="kijkwijzer16+">
                Kijkwijzer 16+
            </span>
      
        </li>
```
```html
        <li class="guidelines">
            
            
            <span data-icon-single="kijkwijzer12+">
                Kijkwijzer 12+
            </span>
      
        </li>
```
Logos for `product-placement`, `kijkwijzerAL`, `kijkwijzer12+` and `kijkwijzer16+` are available as encoded SVG/XML data in the css file: https://www.vrt.be/etc.clientlibs/vrtvideo/clientlibs/site.min.css

**Comment by dagwieers** [comment]
Bummer, let's close it and revisit in the future.
Maybe even reach out to VRT at some point?

**Comment by mediaminister** [comment]
I noticed that PG/PP info is not available in the VRT NU Android app. At some point in the future VRT will add this also on Android and I think they will have to move this info to an API.
