### ISSUE TITLE
navigate to a program example request

### ISSUE THREAD

**Issue by DCL777** [pietje666/plugin.video.vrt.nu#513]
### I would like to navigate in Kodi to a program, so i can choose the episode manually ###

First at all: Thank you very much for the nice work you do here!

I found a nice description of the API here but not how i should use it in Home Assistant or via Curl

Is it possible to provide an example?

API ref: https://github.com/pietje666/plugin.video.vrt.nu/wiki/Automation

This is not working:
![image](https://user-images.githubusercontent.com/55956951/66273121-59612d00-e871-11e9-805f-bfb8e580a054.png)

This is working, but it's to play life TV;
![image](https://user-images.githubusercontent.com/55956951/66273183-eb693580-e871-11e9-9bb5-0d78225fe2a0.png)

Thanks
Dries

**Comment by dagwieers** [comment]
The URL you are using is correct, but I think the **Player.Open** action is supposed to work for playback, not for virtual directory listings. From testing with the CLI tool, I get:

```output
[dag@moria plugin.video.vrt.nu]$ ./test/run.py /programs/tik-tak
** Running URI: plugin://plugin.video.vrt.nu/programs/tik-tak
» * Alle seizoenen → /programs/tik-tak/allseasons
» Seizoen 2019 → /programs/tik-tak/2019
» Seizoen 1981 → /programs/tik-tak/1981
-=( -------- )=-
```

And:
```output
[dag@moria plugin.video.vrt.nu]$ ./test/run.py /programs/tik-tak/allseasons
** Running URI: plugin://plugin.video.vrt.nu/programs/tik-tak/allseasons
-=( Tik-Tak )=-
· Aflevering 53 → /play/id/vid-10aa5685-fbaf-44dc-85ae-0dfe4d3628e0/pbs-pub-b5f0a768-1ed0-426e-a964-8640703e19b8
· Aflevering 55 → /play/id/vid-73ec577e-82f2-4b94-b382-3b83e07f4c1a/pbs-pub-6af1c3aa-fc42-4374-a1fa-594aa3c9ac7c
· Aflevering 21 → /play/id/vid-eb792278-c727-4cbc-96f6-2292125e05ca/pbs-pub-3acba2a3-b545-4488-929d-c45188cfe65a
· Aflevering 23 → /play/id/vid-ca308d43-58eb-4e7a-8f84-34b9142d7b6a/pbs-pub-6eaaebf1-0c99-44fe-a374-7f9f8ff65d93
· Aflevering 52 → /play/id/vid-c4624c57-a83e-40fa-b66d-1d3e50e828e3/pbs-pub-55679b9b-bcc1-4e07-b035-2f11f576f5c3
· Aflevering 2 → /play/id/vid-a5b2528f-cde2-414a-b301-b6714f2ccc2c/pbs-pub-58f49236-ead3-499a-8912-f37ca04c1061
· Aflevering 4 → /play/id/vid-8c33679c-1f1c-4454-8cc6-cddf8dad8cbf/pbs-pub-a25bb945-de85-4426-b389-ba528fd7245a
· Aflevering 26 → /play/id/vid-ad69a38d-74d3-450c-96e8-273d0e9a94e7/pbs-pub-f0dea9c0-bfde-445c-895c-a0ab9dd9b2d9
· Aflevering 22 → /play/id/vid-ae023a52-15e4-43d1-9938-e06e498a6e21/pbs-pub-4273db8e-4a66-431c-ae13-7de7e385a121
· Aflevering 3 → /play/id/vid-82092687-7d58-450a-b134-733c103a9a0d/pbs-pub-898511d3-3a57-4ef5-8672-b0080fb7cdc6
· Aflevering 25 → /play/id/vid-6385372b-70e3-4936-ae1e-4709efd10cc4/pbs-pub-18fcc016-9fa8-4e12-a12e-cc1fc134882d
· Aflevering 51 → /play/id/vid-c738e46c-6eb5-42fa-a8aa-b8979ef2a807/pbs-pub-21921da4-1445-4ac2-8e77-d120969f0824
· Aflevering 54 → /play/id/vid-f99aa588-209d-4808-ae5c-e435586f8aac/pbs-pub-e957c688-16a0-497f-a6ff-ab98c22caeb7
· Aflevering 24 → /play/id/vid-b1377fb3-5ba5-45c4-96c4-e560e6b70877/pbs-pub-289640d9-c6d2-4991-b9b1-ddaef57e3402
· Aflevering 1 → /play/id/vid-986620fb-4cca-41d9-b5c8-bdabf8b2dc82/pbs-pub-29dfeb92-52ef-467b-bc73-b77f0bcdbd54
-=( -------- )=-
```

And testing with kodi-send, I can do:
```bash
$ kodi-send -a 'RunAddon(plugin.video.vrt.nu,/programs/tik-tak/allseasons)'
```

Doing the same using curl:
```bash
curl -X POST -H "content-type:application/json" http://localhost:8080/jsonrpc -d '{ "jsonrpc": "2.0", "method": "Addons.ExecuteAddon", "params": {"wait": true, "addonid": "plugin.video.vrt.nu", "params": ["/programs/tik-tak/allseasons"] }, "id": 1 }'
```

**Comment by dagwieers** [comment]
I will add an example like this to the Wiki API page.

**Comment by mediaminister** [comment]
@DCL777 You should replace `Player.Open` with` GUI.ActivateWindow` and add a slash after 2019 (for an obscure reason there is always a slash needed if the last variable in the url is a number)

Example with curl:
```
curl -X POST -H "content:8080/jsonrpc -d '{"jsonrpc": "2.0", "method": "GUI.ActivateWindow", "params": {"window": "videos", "parameters": [ "plugin://plugin.video.vrt.nu/programs/tik-tak/2019/" ]}, "id": "1"}'
```

**Comment by dagwieers** [comment]
We opened an issue for that obscure problem at: https://github.com/xbmc/xbmc/issues/16516

**Comment by dagwieers** [comment]
I added both examples to the Wiki Automation page at:
https://github.com/pietje666/plugin.video.vrt.nu/wiki/Automation

Feel free to add or propose improvements.

**Comment by DCL777** [comment]
Yes, it's working.  Thanks a lot.

Here's my working Home Assistant code:
automations.yaml:
![image](https://user-images.githubusercontent.com/55956951/66335319-1d929a00-e93b-11e9-9998-dcf2eab9f906.png)

Alternative:  Curl command:  some magic with ',",backslash"
configuration.yaml:
![image](https://user-images.githubusercontent.com/55956951/66335823-17e98400-e93c-11e9-8a82-cb22bbb36328.png)

automations.yaml:
![image](https://user-images.githubusercontent.com/55956951/66335406-43b83a00-e93b-11e9-9756-0b13f76cfb38.png)
