### ISSUE TITLE
Categories no longer works

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#55]
**Describe the bug**
Probably a parsing bug because the website changed again.

**To Reproduce**
1. Go to 'Categories'
2. Click on '.Categories'
3. See empty listing

**Expected behavior**
See the category list.

**(please complete the following information):**
 - LibreELEC v8.95.002
 - Kodi v18.0-RC4

**Log (if available)**
There is no error in the logs.

**Comment by pietje666** [comment]
The site gives back empty categories as well. So its a vrt nu issue. But i will leave this open until it is working again. I wonder if they bring it back up if it will still works the same.

**Comment by michaelarnauts** [comment]
The mobile app seems to be fine. Maybe the app has a more stable API that we can use?

**Comment by pietje666** [comment]
> The mobile app seems to be fine. Maybe the app has a more stable API that we can use?

I would be glad to use one, i decompiled the app once but did not find out how it gets its data. If someone has more info about an Api and how to call it it would be great :)

**Comment by mediaminister** [comment]
You can use the search api:

For example: https://search.vrt.be/search?facets[categories]=koken&buckets[programs]=dagelijkse-kost

**Comment by dagwieers** [comment]
That information is not available from https://services.vrt.be ?

**Comment by pietje666** [comment]
fixed in #56

**Comment by pietje666** [comment]
for api discussions i created #57 so elaborate any further info there :)
