### ISSUE TITLE
Can't play any video

### ISSUE THREAD

**Issue by keiem** [pietje666/plugin.video.vrt.nu#556]
I can browse VRT-NU, but if we want to play something we get a error message: VRT-NU fout
So for some reason it willnot play any content.  The error started 2 days ago. 

- Operating system: CoreElec 9.2.0
- Kodi version: 18.4
- Addon version: 2.2.3
- Using a VPN: no
- Country you are using the addon from: Belgium

**Comment by mediaminister** [comment]
I tested 2.2.3 in LibreELEC 9.1.502 and there are no problems with the streams.

Can you please provide a full debug log: https://discourse.coreelec.org/t/how-to-report-an-issue-youre-having-with-coreelec/3022

**Comment by keiem** [comment]
Hello,

I made a log, see this link: http://ix.io/209P

**Comment by dagwieers** [comment]
@keiem It appears to be the same issue as #554 and we think #558 is the fix.

By any chance did you install a development snapshot, or did you download the v2.2.3 release zip?

**Comment by keiem** [comment]
I was on 2.2.3 and a few days ago the streams wouldn't play anymore.  I tought to fix it with installing a snapshot, but it didn't help.

**Comment by dagwieers** [comment]
Is by any chance your disk full?
Did you try clearing the caches from the **Settings** » **Expert** menu?

**Comment by keiem** [comment]
I installed the latest master without succes.  The disk is OK, +50GB.  I don't find how to clear the cache.  I don(t find this option in expert mode.

**Comment by mediaminister** [comment]
Just open add-on settings and click the following menus:
Expert --> Clear VRT tokens
Expert --> Verwijder VRT-tokens

**Comment by keiem** [comment]
Yes,
clearing VRT tokens helped solving it.  What are these VRT tokens?

**Comment by mediaminister** [comment]
Tokens are small text files that contain information to authenticate the user to different VRT NU services, like getting the stream urls or getting your favourite program list. Tokens are in fact the same as the cookies in a webbrowser.

The add-on caches these tokens to disk to make sure video streams start as fast as possible.

**Comment by dagwieers** [comment]
I am going to close this in favor of #554 (the title is more specific for people to identify).
