### ISSUE TITLE
Changes to settings do not take effect immediately

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#560]
### Describe the bug ###
Most of the changes to the settings require you to restart the add-on (which means first starting another add-on, then return to VRT NU). This is not very user-friendly (i.e. most people would think restarting the add-on would do the trick).

So it's safe to say that people would consider this a bug (changing settings doesn't have any effect). And especially for logging this is problematic, if you enable debug-logging in Kodi, our add-on wouldn't act on it.

We need to address this before releasing v2.3.0.

### To Reproduce ###
1. Change logging settings
2. Continue using the add-on
3. Or restart the add-on
4. Logging changes do not have any effect

### Expected behavior ###
We need to rethink this. Either reevaluate config-options on use (slower) or reevaluate settings when changes are detected.

### Additional context ###
- Operating system: LibreELEC 9.2 Beta2 (9.1.502)
- Kodi version: 18.4
- Addon version: 2.3.0 (devel branch)
- Using a VPN: no
- Country you are using the addon from: BE

**Comment by mediaminister** [comment]
This is not fixed yet.  When enabling and disabling `useresumepoints` setting I get wrong values which causes problems with menu refreshing and the Kodi watched status.

I think the pluginsource entrypoint should be restructured according to Kodi's recommendations:
> The `<reuselanguageinvoker>` element is a feature introduced with Kodi 18.0 that changes the way the python invoker works in Kodi - trying to reuse the invoker instances as much as possible. As a result, the addon performance is greatly improved. **However, note that for the element to work some changes may be required in your addon. Namely, since the invoker is reused, make sure sys.argv is always passed to your entrypoint and propagated throughout your codebase. Do not store it as a class variable.**

**Comment by mediaminister** [comment]
@dagwieers I found out that removing the global `kodi` variable in `addon.py` fixes this problem, but I'm not sure I have the right fix, the following looks rather strange to me:
```
VRTPlayer(KodiWrapper(globals())).show_main_menu()
```

Any suggestions?

**Comment by dagwieers** [comment]
So one solution might be that:
- `get_setting()` reads from the Window property cache first (and uses ADDON second)
  - (and also updates the Window property cache if it access ADDON settings)
- service.py populates the Window property cache when `onSettingsChanged`
  - iterating over all known settings

The drawback here is that we add quite some complexity for something that really ought to be something simple.

**Comment by dagwieers** [comment]
Another more simple solution is to instantiate Addon from addon_entry.py so that it is at least reread once every invocation.

**Comment by dagwieers** [comment]
> Another more simple solution is to instantiate Addon from addon_entry.py so that it is at least reread once every invocation.

I tried this, declare `ADDON = Addon()` in *addon_entry.py*, then import it in *kodiutils.py*. You would expect this to ensure ADDON is always fresh for every invocation. But it isn't for some strange reason.

**Comment by dagwieers** [comment]
The irony is that the easiest solution is to disable reuselanguageinvoker. I don't see any noticeable performance degradation because we designed the add-on in such a way that it is pretty lean already. Only import the stuff we really need.
