### ISSUE TITLE
Use VRT NU API instead of scraping

### ISSUE THREAD

**Issue by pietje666** [pietje666/plugin.video.vrt.nu#57]
As the title says, it would be alot nicer to use an API instead of scraping from the VRT.NU site. 
It would make the addon more stable and most likely be faster.

The problem is, we (or atleast i) do not know which API, nor how to call it.
So any help is welcome!

**Comment by mediaminister** [comment]
I did a little research.

I found out VRT uses some kind of [Elasticsearch](https://www.elastic.co/). I succeeded to get an error message that shows some info about the backend
https://search.vrt.be/search?facets[programUrl]=test&facets[programUrl]=test

I'm not sure which Elasticsearch version or variant VRT uses. I looked at the [Elasticsearch Uri Search documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-uri-request.html) and found out that some parameters work but others don't.

There are two endpoints, a suggest api to get short program info:
https://search.vrt.be/suggest?q=waes
and a search api to get all program info
https://search.vrt.be/search?q=waes

I rewrote the show_videos function using this api as an example:
https://github.com/mediaminister/plugin.video.vrt.nu/blob/c4ff617335ddb2322fcc9c1c7f1d57171166153a/plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py#L95

The possibilities with this api seem endless, but I have to examene this further.

**Comment by mediaminister** [comment]
I get 241 items with the following request:
https://search.vrt.be/suggest?facets[transcodingStatus]=AVAILABLE

I think this corresponds to the a-z list.

I have not yet found a good query for the categories list.

**Comment by pietje666** [comment]
Looks good for A-Z

**Comment by pietje666** [comment]
for the categories tis seems to be working, i guess the categories are hardcoded => https://search.vrt.be/search?size=150&facets[categories]=docu needs to be mixed with the available facet though

**Comment by pietje666** [comment]
i want to do something this https://search.vrt.be/search?size=150&facets[categories]=docu&select=program&distinct i think it must be possible in some way.

**Comment by mediaminister** [comment]
I tried a lot of different things but did not find a method to get a list of categories. I think this public api is limited. Take a look at this document: https://www.vrt.be/etc/clientlibs/components/search.js

I publish my experiments with this api on: https://github.com/mediaminister/plugin.video.vrt.nu/tree/api

**Comment by mediaminister** [comment]
Summary of my api experiment (https://github.com/mediaminister/plugin.video.vrt.nu/tree/api):

I rewrote the following functions using the api
- az list: [https://vrtnu-api.vrt.be/suggest?facets[transcodingStatus]=AVAILABLE](https://vrtnu-api.vrt.be/suggest?facets[transcodingStatus]=AVAILABLE)
- program list by category: [https://vrtnu-api.vrt.be/suggest?facets[categories]=humor](https://vrtnu-api.vrt.be/suggest?facets[categories]=humor)
- detect multiple seasons by facets/buckets in episode list: [https://vrtnu-api.vrt.be/search?i=video&size=150&facets[programUrl]=//www.vrt.be/vrtnu/a-z/fc-de-kampioenen/](https://vrtnu-api.vrt.be/search?i=video&size=150&facets[programUrl]=//www.vrt.be/vrtnu/a-z/fc-de-kampioenen/)
- list episodes from season: [https://vrtnu-api.vrt.be/search?i=video&size=150&facets[programUrl]=//www.vrt.be/vrtnu/a-z/fc-de-kampioenen/&facets[seasonTitle]=2](https://vrtnu-api.vrt.be/search?i=video&size=150&facets[programUrl]=//www.vrt.be/vrtnu/a-z/fc-de-kampioenen/&facets[seasonTitle]=2)

I also extended the metadatacreator class to provide more info in videoplayer view: episode number, season number, tvshowtitle, etc...

I also used the screenshot api ([https://vrtnu-api.vrt.be/screenshots/een.jpg](https://vrtnu-api.vrt.be/screenshots/een.jpg)) to provide a picture with the livestreams, but the picture doesn't refresh.

Besides the categories list and urltostream class, everything works now through the api. I have currently no more spare time to refactor my code using vrtapihelper class. Maybe in the next weeks, but feel free to rewrite my code. Most of the work has already been done.

I noticed `publicationId` and `videoId` is also present in this api, so we don't need web scraping anymore in the urltostream class.

**Comment by pietje666** [comment]
I will take what i need thanks, will also refactor code to use season facet filtering right now i do it manually in the code but indeed it would be better to do it directly in the searchstring!

but those fixes are for a later stage right now i will already push a new version!

**Comment by mediaminister** [comment]
I luckily found some time to create a pull request in which I have implemented all the functions mentioned: https://github.com/pietje666/plugin.video.vrt.nu/pull/64

**Comment by dagwieers** [comment]
@mediaminister I just tested your new release and it works fine. I like the new addition of **Most recent**, but I was wondering if it would be possible to also add a **Channels** section where programs are listed by channel (Ketnet Junior, Ketnet, Sporza, etc...).

That would be nice for adding to the favourites in the profile of our children.

**Comment by mediaminister** [comment]
This is possible, for instance: 50 most recent episodes from ketnet: https://vrtnu-api.vrt.be/search?i=video&size=50&facets[transcodingStatus]=AVAILABLE&facets[brands]=ketnet

I just have to find out how I can dynamically get all vrt brand names with one http request. I didn't find an efficient way of getting these brand names from the api. So, I might have to scrape them from the vrt nu website.

**Comment by pietje666** [comment]
more features = more maintenance :( , first thing to do is actually make the code python 2-3 compatible (otherwise no more updates from kodi team).  I have done some work already to establish that but its not working yet. Maybe first ill review your pull request and then perform the conversion again

**Comment by mediaminister** [comment]
I agree, I'm not coding at the moment. Maybe we can open another issue to discuss the difficulties with python 2-3 compatibility. If I'm not mistaken python 2 is supported until the end of this year.

**Comment by pietje666** [comment]
https://github.com/xbmc/repo-plugins/pull/2331 => this add-on isn't Python 3 compatible. Future updates have to be compatible with Python 3.

**Comment by dagwieers** [comment]
@pietje666 I have some standard [Travis integration for Kodi addons](https://github.com/dagwieers/screensaver.turnoff), can I add it to this project?

It does include PEP8-related stuff, so it would require a general cleanup as well. Unfortunately, we can't do any proper code-testing since the xbmc imports fail anyhow. I would prefer this PR is merged before this gets added.

**Comment by dagwieers** [comment]
BTW I have a lot of experience with python2/3 issues, and it's not that hard to make it work.

**Comment by pietje666** [comment]
> @pietje666 I have some standard [Travis integration for Kodi addons](https://github.com/dagwieers/screensaver.turnoff), can I add it to this project?
> 
> It does include PEP8-related stuff, so it would require a general cleanup as well. Unfortunately, we can't do any proper code-testing since the xbmc imports fail anyhow. I would prefer this PR is merged before this gets added.

Everything can be unit tested except the kodiwrapper.py / addon.py class. About the Pep 8 fine by me as long as it does not enforce the max line length rule.

**Comment by dagwieers** [comment]
> About the Pep 8 fine by me as long as it does not enforce the max line length rule.

Perfect, I have it ready.

**Comment by pietje666** [comment]
The script will execute automatically if something gets pushed/pullrequested ? Or how does it work?

**Comment by dagwieers** [comment]
You need to enable your repository on travis-ci.org, and from that moment any PR will show the CI test status. At the moment it will likely fail because not all pylint tests were fixed. If you enable it, I will make a PR that will become green because it fixes those.

**Comment by mediaminister** [comment]
Okay, thanks for setting up a wiki page. I'll add more information soon.

**Comment by mediaminister** [comment]
Found something new:
You can use dot notation in facets to navigate a level deeper in the json data:
https://vrtnu-api.vrt.be/search?i=video&facets[programTags.title]=Kinderen

**Comment by mediaminister** [comment]
While looking for possibilities to phase out web scraping completely, I found something new:
You can use dot notation in facets to navigate a level deeper in the json data:
https://vrtnu-api.vrt.be/search?i=video&size=1&facets[programTags.title]=Kinderen

**Comment by mediaminister** [comment]
Phasing out web scraping completely is not around the corner. I found out that the category images at https://www.vrt.be/vrtnu/categorieen/ are not available through https://vrtnu-api.vrt.be/search?i=video

**Comment by dagwieers** [comment]
But the category images are an optional feature, so as long as the addon does not fail if this no longer works, I think we are fine.

**Comment by dagwieers** [comment]
@pietje666 Can we open the Wiki for outsides, or at least give @mediaminister the right privileges to update the Wiki ?

**Comment by dagwieers** [comment]
@mediaminister What I was looking for in the interface was something equivalent to this: https://stackoverflow.com/questions/25465215/elasticsearch-return-unique-values

This could allow to list categories, channels/brands, etc...

**Comment by mediaminister** [comment]
The api frontend is not Elasticsearch, VRT wrote it's own limited frontend.
Check this error message: https://vrtnu-api.vrt.be/search?i=video&facets[x][x]

I can get a list of categories by running through 500 video items, but it's slow and needs a local cache and it's useless without the images.

Maybe rewriting the web scraping code to make it more failsafe is a better idea.

**Comment by dagwieers** [comment]
Personally I wouldn't mind if we hard-coded the known list of categories, and translate them, and use this:
1. as a fallback mechanism for when the scraping fails
2. for translating to other languages

PS It would be nice if the translation-mechanism in Kodi would not depend on numbers, but on strings instead, it would make our code *a lot more readable*.

**Comment by dagwieers** [comment]
I wrote a fallback mechanism for categories and included a web-scraping test to find discrepancies between online and internal representation. You can find it in #161 

The only thing that remains requiring web-scraping is the livestream implementation.

**Comment by dagwieers** [comment]
Apart from #161 I don't think there is a lot we can do.
