### ISSUE TITLE
Mark as watched when Up Next notifies to play next episode

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#571]
### Describe the feature ###
Currently, if you select to start the next episode in Up Next, you may end up with the current episode in the **Continue watching** list because it has not been watched until the end.

We ought to mark the currently playing episode as watched before playing the next episode.

**Comment by dagwieers** [comment]
I looked at this, but it is not clear to me how I can send a different event to the player to achieve this.

Kodi is not making things easy for us.

**Comment by mediaminister** [comment]
>  if you select to start the next episode in Up Next, you may end up with the current episode in the Continue watching list because it has not been watched until the end.

Continue watching list  is filled with items from  VRT NU resumepoints API, so we only need to push a player position that differs less than 30 seconds from the total time.

This is already implemented for "Up Next" with the event `onPlayBackResumed` and can be seen in the logs:
`[plugin.video.vrt.nu] [PlayerInfo] 74 onPlayBackResumed after playlist change`

There might be a bug where the called back player position differs more than 30 seconds from the total time and the episode gets listed in Continue watching.
But, currently I can't reproduce your issue with the master branch.

**Comment by mediaminister** [comment]
@dagwieers Do you have more details about possible invalid items in the "Continue watching" list?
I tested the master branch on Linux and Windows and I never got invalid items.

**Comment by dagwieers** [comment]
I think we can close this and reopen if I see this happen again. The code has evolved a lot since.
