### ISSUE TITLE
Addon fails to work

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#60]
**Describe the bug**
I noticed yesterday-evening that this addon no longer worked.
After reproducing this on a second set, I noticed the logs show: `ERROR: ADDON: Could not locate inputstream.adaptive.so.2.3.15`

The same happens for any other stream and also happens on a second setup.
It seems to be related to a recent adaptive inputstream update ?

Netflix addon is still working fine.
It was the Netflix addon that triggered the update of the adaptive inputstream on this system IIRC.

**(please complete the following information):**
 - Operating system: LibreELEC (official): 9.0.0, kernel: Linux ARM 32-bit version 4.19.17
 - Kodi Version: Kodi (18.0 Git:newclock5_18.0-Leia). Platform: Linux ARM 32-bit

**Additional context**
- Using a VPN: No
- Country you are using the addon from: BE

**Log (if available)**
```
15:17:03.899 T:1420817264  NOTICE: /storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/XVRTToken
15:17:03.900 T:1420817264  NOTICE: /storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/ondemand_vrtPlayerToken
15:17:04.234 T:1420817264  NOTICE: protocol: mpeg_dash
15:17:04.355 T:1937694736  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.vrt.nu/?action=play&video=%2Fvrtnu%2Fa-z%2Fde-zevende-dag%2F2019%2Fde-zevende-dag-d20190224%2F
15:17:04.356 T:1757098864  NOTICE: Creating InputStream
15:17:04.357 T:1757098864   ERROR: ADDON: Could not locate inputstream.adaptive.so.2.3.15
15:17:04.358 T:1757098864   ERROR: IAddonInstanceHandler::CreateInstance: inputstream.adaptive returned bad status "Permanent failure" during instance creation
15:17:04.358 T:1757098864   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.vrt.nu/?action=play&video=%2Fvrtnu%2Fa-z%2Fde-zevende-dag%2F2019%2Fde-zevende-dag-d20190224%2F]
15:17:04.358 T:1757098864  NOTICE: CVideoPlayer::OnExit()
15:17:04.564 T:1937694736  NOTICE: CVideoPlayer::CloseFile()
15:17:04.564 T:1937694736  NOTICE: VideoPlayer: waiting for threads to exit
15:17:04.564 T:1937694736  NOTICE: VideoPlayer: finished waiting
```

**Comment by pietje666** [comment]
Actually i use the same inputstream helper addon that netflix uses. So i wonder if they do something special?
Which version of my addon do u use? 
Do you use a special version of the netflix addon?
Btw i am in the progress of buying a house so i do not have alot of time to investigate it right now.

**Comment by dagwieers** [comment]
TBH Something weird is going on. The log file on my other device was saying: `ERROR: ADDON: Could not locate inputstream.adaptive.so.2.3.13` while 2.3.15 appeared to be installed.

I then tried to reinstall it, and it failed showing no addon. Reinstalling 2.3.15 could not be installed, but 2.3.13 did but it showed as 2.3.15. After rebooting 2.3.15 did no longer show up in the list of addons, only 2.3.13, so after installing 2.3.13 again everything worked again.

I haven't looked into the second device which reported issues with 2.3.15. I have a MySQL backend for Kodi and maybe something is stored in MySQL that conflicts and breaks my setup ? But it appears not to be related to the VRT.NU addon but rather something system-related.
