### ISSUE TITLE
Addon proxy support

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#63]
**Describe the feature**
I would like to be able to use a proxy specific for this addon. So that other addons can work without a proxy. This is to better make use of the bandwidth for an elementary school's Internet connection. Classes usually visit the same streams every day e.g. Karrewiet etc.

We currently plan to do this on the proxy-level, but that makes us dependent on the proxy for everything. So if there's an issue with the proxy, everything is impacted also the stuff that we don't need proxied. It would be more efficient and a better design if we can do this just for this addon.

**Comment by mediaminister** [comment]
Just configure your proxy server to proxy only specific domains.
Streaming data for VRT NU uses the following domains:
ondemand-cf-vrt.akamaized.net
live-cf-vrt.akamaized.net

I don't see the point of implementing this function into the addon.
But feel free to do so, I'm just not going to implement this myself.

**Comment by dagwieers** [comment]
If Kodi supported WAP (Web Auto Proxy) support, that would be of help to us, but doing this at the proxy level does not help. It would only allow to say what should be cached and what not, but it would still depend on the proxy being available all the time (becoming critical infrastructure for any access, even local access).

Thanks for listing the domains, I captured these already from the logs, but it's nice to see them confirmed :-)

**Comment by dagwieers** [comment]
Thinking about this either PAC and WPAD support, or doing it at the Kodi level (where you could have different proxy-settings for different addons) would probably make more sense.

At least it makes it possible to reuse the same configuration for multiple addons (either on a domain basis with PAC, or by reusing proxy-profiles per addon).
