### ISSUE TITLE
LGTM warnings/suggestions

### ISSUE THREAD

**Issue by michaelarnauts** [pietje666/plugin.video.vrt.nu#655]
### Describe the bug ###
I've recently discovered lgtm and its code analisys.

There is a report for vrt nu here: https://lgtm.com/projects/g/pietje666/plugin.video.vrt.nu/alerts?mode=list

There are 6 related warnings and one suggestion that might or not might be a bug. It could be worth checking out.

The service is free for open source projects.

**Comment by dagwieers** [comment]
None of the reported issues are actual issues AFAICT.

I forgot about lgtm but it is nice we haven't introduced any major issues 😉

**Comment by dagwieers** [comment]
I also ran our code through sonarcloud just to see what it would report: https://sonarcloud.io/dashboard?id=dagwieers_plugin.video.vrt.nu

Things are looking good :-)

**Comment by dagwieers** [comment]
I added both links to our [Test plan](https://github.com/pietje666/plugin.video.vrt.nu/wiki/Test-plan) wiki page.
