### ISSUE TITLE
Migration to Python 2/3-compatible addon

### ISSUE THREAD

**Issue by mediaminister** [pietje666/plugin.video.vrt.nu#66]
In this issue we can discuss  the migration proces to a Python 2-3 compatible addon.

I think we definitely need to add the kodi.six library. Any ideas on this? https://github.com/romanvm/kodi.six

Secondly we need to import the Future library like this:
```
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

from future import standard_library
standard_library.install_aliases()
from builtins import str
```

We can look at https://github.com/skipmodea1/plugin.video.tweakers as an example

**Comment by pietje666** [comment]
In my test environment i was using future and the futurize utility as described here => https://kodi.wiki/view/General_information_about_migration_to_Python_3 (6.2)

**Comment by dagwieers** [comment]
I don't think we need a shebang, since you can't run any of these files on the commandline anyway.

**Comment by pietje666** [comment]
@dagwieers i saw already alot of future imports, does it mean alot of the conversion has been done already?

**Comment by dagwieers** [comment]
@pietje666 No, these are mostly blank statements now, but they are intended to make Python 3 code work on Python 2. TBH I think most of the code is fine now. The only real thing I fixed was urlencode.

**Comment by dagwieers** [comment]
We will only know for sure if it works on a Python 3 Kodi, since we cannot actually run the addon.
The unit tests reveals some stuff, but not everything.

**Comment by pietje666** [comment]
i think we can test it with one of those mirrors http://mirrors.kodi.tv/test-builds/windows/win64/

**Comment by dagwieers** [comment]
One more fix was added in #69 for urljoin.

**Comment by dagwieers** [comment]
> i think we can test it with one of those mirrors http://mirrors.kodi.tv/test-builds/windows/win64/

These builds still seem to be using Python 2.7. Could it be that the Kodi devs are just jumping the gun about Python 3 support ? Still would be nice to be able to run Kodi addons without actually running Kodi (for testing purposes).

**Comment by dagwieers** [comment]
> i think we can test it with one of those mirrors http://mirrors.kodi.tv/test-builds/windows/win64/

Ok, I downloaded the latest version. I didn't notice there were specific Python3 builds. Trying again ;-)

**Comment by dagwieers** [comment]
I found official packages in the *migration* repository at: https://mirrors.kodi.tv/addons/migration/script.module.beautifulsoup4/

I guess the problem is that the Kodi 18.2 Leila build is using the (Python2) repositories.
