### ISSUE TITLE
Episodes not marked as watched using Up Next

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#661]
### Describe the bug ###
When watching multiple episodes of **Vrede Op Aarde** in succession using Up Next, the episodes were not marked as watched as one would expect.

### Additional context ###
- Operating system: LibreELEC v9.2.0
- Kodi version: Kodi 18.5
- Addon version: v2.3.0
- Using a VPN: no
- Country you are using the addon from: BE

**Comment by dagwieers** [comment]
Saw this again, watched 2 first episodes of **Zie mij graag** in quick succession using Up Next and only the first episode was marked as watched. It actually started to play the third episode when we stopped, but the second episode was not marked as watched.

**Comment by dagwieers** [comment]
I would like to get v2.3.1 out as soon as possible. Not sure if we have an easy fix for this issue.

**Comment by dagwieers** [comment]
After watching **Night of the Proms 2019** (oneoff) from the **Watch later** menu, the video was marked as watched in Kodi, but it was not removed from the Watch later listing (so not marked as watched in VRT NU).

**Comment by mediaminister** [comment]
Not removing "Up Next" resumepoints is a possible solution, implemented in https://github.com/pietje666/plugin.video.vrt.nu/pull/676
