### ISSUE TITLE
Episode of De Canvas popnacht are marked as oneoff

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#670]
### Describe the bug ###
On VRT NU the De Canvas popnacht show was one long video, but today was also cut into smaller 5mins and 10mins episodes. Because it originally was (correctly) tagged **oneoff**, the episodes are each tagged as **oneoff** as well. Which causes all episodes to be listed in the main Programs view.

On the website both the long show as well as the episodes are shown correctly, but they do not have the ability to show oneoff's and tvshows in the same listing. If you disable this feature, things work out correctly in our add-on as well.

The long video of the show will be removed in 7 hours, so hopefully then the **programType** will be corrected to become **reeksoplopend**.

https://search.vrt.be/search?size=150&q=de-canvas-popnacht

**I reported this to VRT NU.**

**Comment by dagwieers** [comment]
VRT NU has confirmed and fixed the issue.

Despite this it might be worthwhile to avoid this in the future by not just considering `programType`, but also look at `episodeNumber` (if not 1, it is likely not a oneoff) and `seasonNbOfEpisodes`.

Maybe we need a new concept/term for what we today call a oneoff, and add those conditions. Ideas welcome...

**Comment by mediaminister** [comment]
I checked all `oneoff` episodes with a small script and found out the following:

- `episodeNumber` is `0` or `1`
- `seasonNbOfEpisodes` is always `0`
- `seasonTitle` and `seasonName` are equal and always have the value of a year (YYYY)

I suspect that some keys in VRT NU api are automatically initiated with value `0`, so only relying on a zero value to make a decision is a bad idea.
There is also a possibility that `seasonTitle` or `seasonName` doesn't contain the value of a year.

I think this Canvas Popnacht bug can be avoided by just adding a `episodeNumber` filter like this:

https://vrtnu-api.vrt.be/search?size=150&facets[programType]=oneoff&facets[episodeNumber]=[0,1]

**Comment by dagwieers** [comment]
@mediaminister I was hoping for something like this (either this, or filtering them out when processing). I will make this change and add comments to clear up why we decided to do this.

**Comment by mediaminister** [comment]
Sorry, I checked again and the solution I suggested does not work very well. The episodeNumber filter just takes the first episode of a `oneoff` and ignores whether there are more episodes.

**Comment by dagwieers** [comment]
But a oneoff should not have more than one episode, so this should work just fine. I didn't see any deficiencies while testing.

**Comment by mediaminister** [comment]
It doesn't solve the popnacht case, if a `oneoff `wrongly has multiple episodes, only the first episode is listed. 

I think it's better to treat a bad `oneoff` with multiple episodes as a normal program.

**Comment by dagwieers** [comment]
Well, this at least doesn't cause them all to be listed in the main A-Z listing. But indeed, the problem here is that we take the properties of the first entry and assume they match all entries. There is no good solution for this, as we don't know which entry is the best one to use IMO.

**Comment by mediaminister** [comment]
Okay, maybe there exists a better solution, maybe not. But it's definitely not worth the effort to implement difficult workarounds for VRT mistakes.

**Comment by dagwieers** [comment]
I agree. It is better to report these issues when they arise anyway.

**Comment by dagwieers** [comment]
Another similar issue. First ZOOks was added as a 4-episode series (while it actually is a movie). Now it is also added as a movie, but listed together with the episodes of the series. Because we take the properties of an episode for all the items.

So it is debatable if these are actual mistakes by VRT. They simply mix oneoff's with multi-episode series and our code doesn't allow for this. A program name must either be a oneoff, or part of an episode-list, not both.

This problem will also disappear in 6 days when the movie expires.
