### ISSUE TITLE
Add Klara live stream to VRT NU Live TV

### ISSUE THREAD

**Issue by streulma** [pietje666/plugin.video.vrt.nu#683]
Please add the Klara Live webcam stream to VRT NU Live TV addon.

Link to live stream: https://klara.be/live

**Comment by mediaminister** [comment]
Done, you can install this zip file to get the update: [plugin.video.vrt.nu-2.3.2-klaralive-10065cd.zip](https://github.com/pietje666/plugin.video.vrt.nu/files/4135215/plugin.video.vrt.nu-2.3.2-klaralive-10065cd.zip)
