### ISSUE TITLE
niet alles loopt nog

### ISSUE THREAD

**Issue by Chappie66** [pietje666/plugin.video.vrt.nu#690]
sinds kort kan ik niet meer alles van VRT.Nu bekijken via de addon. voorheen liep alles... opeens lopen programmas die volgens mij GeoBlocked zijn niet meer... via internet kan ik ze wel bekijken onder dezelfde inlog (user/password).... wat is hier het probleem ?  Is ongeveer sinds begin Januari..

**Comment by dagwieers** [comment]
We vragen iedereen die een probleem meldt om een aantal vragen te beantwoorden, zodat wij ze achteraf niet opnieuw moeten stellen. U hebt ervoor gekozen om dat allemaal weg te vegen zodat ik u toch moet vragen om alle vragen te beantwoorden.

https://raw.githubusercontent.com/pietje666/plugin.video.vrt.nu/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by Chappie66** [comment]
laat maar zitten... Grieks is nog simpeler



    On Monday, March 2, 2020, 06:18:19 PM GMT+1, Dag Wieers <notifications@github.com> wrote:  
 
 
We vragen iedereen die een probleem meldt om een aantal vragen te beantwoorden, zodat wij ze achteraf niet opnieuw moeten stellen. U hebt ervoor gekozen om dat allemaal weg te vegen zodat ik u toch moet vragen om alle vragen te beantwoorden.

https://raw.githubusercontent.com/pietje666/plugin.video.vrt.nu/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by dagwieers** [comment]
Dus je vraagt van ons een inspanning, maar bent zelf niet bereid die te leveren?
Geen probleem.

**Comment by Chappie66** [comment]
wat moet ik dan allemaal invullen...??  


    On Monday, March 2, 2020, 06:28:08 PM GMT+1, Dag Wieers <notifications@github.com> wrote:  
 
 
Dus je vraagt van ons een inspanning, maar bent zelf niet bereid die te leveren?
Geen probleem.
