### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#70]
Let's use this ticket to discuss code structure and design briefly.

**Comment by dagwieers** [comment]
I think it would be nice if we can add docstrings to all classes, methods and functions.

When I look at the current design, I often don't know why it is done in a certain why (probably because I have limited knowledge of what is needed for the VRT API). The docstrings can help with getting new contributors up to speed when fixing/improving our code.

**Comment by dagwieers** [comment]
What is the purpose of having these files with only variable definitions ?
- kodiwrappers/sortmethod.py
- vrtplayer/actions.py

**Comment by pietje666** [comment]
> What is the purpose of having these files with only variable definitions ?
> 
> * kodiwrappers/sortmethod.py
> * vrtplayer/actions.py

They serve as a wrapper around them so they can be accessed from numerous places without a file taking ownership. Since those variables are used across multiple files. Is there another way to perform this?

**Comment by dagwieers** [comment]
There are a few options, not sure myself what direction we want to take this.
We also define a few @staticmethod's inside clases that could simply be non-class functions.

**Comment by dagwieers** [comment]
I added a list of ideas/thoughts at: https://github.com/pietje666/plugin.video.vrt.nu/wiki

**Comment by dagwieers** [comment]
Closing this issue
