### ISSUE TITLE
Non-breaking whitespace in descriptions

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#77]
**Describe the bug**
In the descriptions of the following programs we can find HTML entities, like `&amp;`, `&nbsp;` or `&#39;`
- My brilliant friend extra's
- Pano
- Pantani - The accidental death of a cyclist
- R.K.eredienst
- The spirit of Hannah Arendt
- Van Gils & gasten muziek
- Villa Politica

I could not detect any in the plots of episodes.

**Comment by mediaminister** [comment]
You can find the html entities in the suggest api. For example, Pano: https://search.vrt.be/suggest?facets[categories]=nieuws-en-actua

**Comment by dagwieers** [comment]
Sure, I wasn't expecting we were inserting these ourselves ;-)
