### ISSUE TITLE
Broken links Ketnet videos

### ISSUE THREAD

**Issue by mdesplenter** [pietje666/plugin.video.vrt.nu#8]
There are a lot of broken links in the Ketnet content. Most of the Movies just won't start playing. Can it be cache related?

**Comment by pietje666** [comment]
Could you provide reproduction steps so i can have a look? Just played some Ketnet files and they seemed to be working on my machine :/.

Also check your logfile to see what error is being logged please

**Comment by mdesplenter** [comment]
Example: the program Dinopoot van only play 'Het ding dat wiebelde' and 'Het ding dat wou slapen'. The other files like 'Het ding dat terugkwam' try to load, but just stop in the proces.

The log shows: 'Failed HTTP returned error 403' and 'skipping unplayable item: 0, path'
I'm using an Android tvbox, and accessing from the Netherlands.

**Comment by pietje666** [comment]
Hmm, 403 weird maybe a region block although normally it should not block anything by region. 

I tested it on my PC, RPI3 and Android phone and everything seemed to work. I have a dutch VPN from work i will test it tomorrow with the dutch VPN. 
Is your android tvbox connected with wifi or cable?

**Comment by pietje666** [comment]
Just checked the Dinopoot using my dutch VPN. As a matter in fact it indeed did not want to play when the VPN was in use. As soon as i turned my VPN off the episodes did play. 

Note: i also tried it on the vrt.nu site directly and there it also did not want to play. 

So this issue must be a region block, maybe you can ask vrt.nu directly why the videos from dinopoot wont play using their site?

**Comment by dagwieers** [comment]
We now display if a video is Geo-blocked in the description pane.
