### ISSUE TITLE
Failes to play

### ISSUE THREAD

**Issue by JeanPoll** [pietje666/plugin.video.vrt.nu#9]
21:10:24.006 T:1563423728   ERROR: CCurlFile::FillBuffer - Failed: Timeout was r                                                             eached(28)
 ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
21:10:55.937 T:1958777776  NOTICE: VideoPlayer: Opening: http://ondemand-w.lwc.v                                                             rtcdn.be/content/vod/vid-dis-f3434b00-112d-46e3-bba4-a3792e10eba1_2/vid-dis-f343                                                             4b00-112d-46e3-bba4-a3792e10eba1_2_nodrm_47b7d5bd-4010-4f74-a8fd-3ee63189bfd0.is                                                             m/.m3u8
21:10:55.937 T:1958777776 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIA                                                             LIZED
21:11:07.965 T:1958777776   ERROR: CCurlFile::Stat - Failed: Timeout was reached                                                             (28) for http://ondemand-w.lwc.vrtcdn.be/content/vod/vid-dis-f3434b00-112d-46e3-                                                             bba4-a3792e10eba1_2/vid-dis-f3434b00-112d-46e3-bba4-a3792e10eba1_2_nodrm_47b7d5b                                                             d-4010-4f74-a8fd-3ee63189bfd0.ism/.m3u8
21:11:07.966 T:1571812336  NOTICE: Creating InputStream
21:11:20.057 T:1571812336  NOTICE: Creating Demuxer
21:11:50.752 T:1571812336   ERROR: OpenDemuxStream - Error creating demuxer
21:11:50.753 T:1571812336  NOTICE: CVideoPlayer::OnExit()
21:11:50.754 T:1958777776   ERROR: Playlist Player: skipping unplayable item: 0,                                                              path [plugin://plugin.video.vrt.nu/?action=play&video=https%3A%2F%2Fwww.vrt.be%                                                             2Fvrtnu%2Fa-z%2Fmarlene-dietrich--le-crepuscule-d-un-ange%2F2012%2Fmarlene-dietr                                                             ich--le-crepuscule-d-un-ange-s2012%2F]
21:11:50.755 T:1958777776  NOTICE: CVideoPlayer::CloseFile()
21:11:50.756 T:1958777776  NOTICE: VideoPlayer: waiting for threads to exit
21:11:50.756 T:1958777776  NOTICE: VideoPlayer: finished waiting
21:11:50.757 T:1958777776  NOTICE: CVideoPlayer::CloseFile()
21:11:50.757 T:1958777776  NOTICE: VideoPlayer: waiting for threads to exit
21:11:50.757 T:1958777776  NOTICE: VideoPlayer: finished waiting
21:12:02.475 T:1580200944   ERROR: CCurlFile::Stat - Failed: Timeout was reached                                                             (28) for http://download.osmc.tv/kodi/addons/krypton/plugin.video.wdrmediathek/i                                                             con.png

**Comment by pietje666** [comment]
Tested on PC and RPI3 and it did work.  Does it work again after you have retried it?

And also what device are you using and using cable or wifi?

**Comment by JeanPoll** [comment]
I will try with clean kodi install later today.
I do use a cable

**Comment by pietje666** [comment]
Any update on the issue?

**Comment by JeanPoll** [comment]
Clean install of osmc did work for me. No idea why it when't wrong.
