### ISSUE TITLE
[Visual] Playing one video marks all videos as playing

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#94]
**Describe the bug**
I noticed that when you are playing one stream in the VRT.NU addon, and while playing return to (any) menu you will see that it appears as if every file is being played.

This is when using the v1.7.0 master branch.

**Comment by mediaminister** [comment]
I can't reproduce this bug. Also master branch.

Screenshot:
![Screenshot at 2019-03-26 17-05-18](https://user-images.githubusercontent.com/45148099/55013496-83e04c80-4fe9-11e9-805f-5bbabe5d292c.png)

**Comment by dagwieers** [comment]
Might have been some of my customizations wrt. InfoLabels. Need to test.

**Comment by dagwieers** [comment]
I am going to close this as it was a local modification causing this.
