### ISSUE TITLE
Please release version 1.7: version 1.6 almost useless cause a-z and categories  list are failing

### ISSUE THREAD

**Issue by mediaminister** [pietje666/plugin.video.vrt.nu#96]
Today, VRT updated the VRT NU website and that made version 1.6 almost useless cause all web scraping functions fail.

Releasing version 1.7 is now urgent.

**Comment by dagwieers** [comment]
We should have released this morning so that there was a higher chance this was available now.

**Comment by pietje666** [comment]
was planning to release tonight anyway. This morning i was working...

**Comment by dagwieers** [comment]
> was planning to release tonight anyway. This morning i was working...

@pietje666 Maybe we could share the responsibility of making releases and set some rules ?
In essence anyone could offer a new version upstream, it's just the release workflow we have to think about.

E.g. if we would tag/branch releases, it would make it easier to backport simple fixes like this one. And we could share the responsibility to keep the Addon working by releasing the most simple fix possible to the existing stable release (only). Which would have caused a v1.6.1 release this morning as a quick fix.

And if we could automate testing (and escalate when it fails) we could even be aware of such breakage before any of the users hit it.

**Comment by dagwieers** [comment]
@mediaminister a-z listing was working fine this morning, and it seems to work still ? It's only Categories that was broken.

**Comment by mediaminister** [comment]
A-z **in version 1.6** gives me an error.

**Comment by dagwieers** [comment]
Also, if we would restructure our code and get rid of plugin.video.vrt.nu sub-directory, anyone could get the fix by downloading the latest zip-file from the repository. I still think we need to allow for this.

**Comment by dagwieers** [comment]
@mediaminister Oh right, v1.6 is broken, yes !

**Comment by pietje666** [comment]
Feel free to create a new version and push it to the Kodi repo i do not mind. I will only be able to make a new version later this evening anyway => cooking => eating..

**Comment by dagwieers** [comment]
Ok, let's discuss about the workflow after this. I think we can keep it lightweight, but still offer the best experience to our users. (And let's get rid of *all* web scraping too ;-))

**Comment by dagwieers** [comment]
The release has been cut, I will be pushing it now to upstream.

**Comment by mediaminister** [comment]
Wait. It probably will fail at https://github.com/xbmc/repo-plugins/pulls

**Comment by mediaminister** [comment]
I made a [pull request](https://github.com/pietje666/plugin.video.vrt.nu/pull/99) with changes to succeed the kodi-addon-checker test at https://github.com/xbmc/repo-plugins/pulls

**Comment by dagwieers** [comment]
Ok, I noticed the ZIP file I pushed had some .orig leftover files included. So I had to make a new one, but the size is a bit (46k) smaller than before it seems: https://github.com/pietje666/plugin.video.vrt.nu/releases

**Comment by dagwieers** [comment]
I verified, almost every file is larger in v1.7.0 and still the ZIP file is smaller. Better compression in Linux ?

Also I noticed we added GPLv2 headers to our code, but the LICENSE and metadata states GPLv3. So that's something to fix later :-/

**Comment by dagwieers** [comment]
Let's hope this gets released soon: https://github.com/xbmc/repo-plugins/pull/2349

**Comment by michaelarnauts** [comment]
@dagwieers and @mediaminister great job on your recent contributions to this plugin!

**Comment by pietje666** [comment]
It has been merged!
